<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="OllamaSharp" Version="5.4.25"/>
    <PackageVersion Include="Microsoft.Extensions.AI" Version="10.4.1"/>
    <PackageVersion Include="Microsoft.Agents.AI" Version="1.0.0-preview.260108.1" />
	<PackageVersion Include="Microsoft.Agents.AI.Abstractions" Version="1.0.0-preview.260108.1" />
	<PackageVersion Include="Microsoft.Agents.AI.Hosting" Version="1.0.0-preview.260108.1" />
    <PackageVersion Include="SonarAnalyzer.CSharp" Version="10.22.0.136894"/>
  </ItemGroup>
</Project>
