<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.5" />
    <PackageVersion Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.5" />
    <PackageVersion Include="Microsoft.AspNetCore.TestHost" Version="10.0.5" />
    <PackageVersion Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.6.2" />
    <PackageVersion Include="Microsoft.Testing.Extensions.TrxReport" Version="2.2.1" />
    <PackageVersion Include="Microsoft.Testing.Platform" Version="2.2.1" />
    <PackageVersion Include="OllamaSharp" Version="5.4.25" />
    <PackageVersion Include="Microsoft.Extensions.AI" Version="10.4.1" />
    <PackageVersion Include="Microsoft.Agents.AI" Version="1.0.0-preview.260108.1" />
    <PackageVersion Include="Microsoft.Agents.AI.Abstractions" Version="1.0.0-preview.260108.1" />
    <PackageVersion Include="Microsoft.Agents.AI.Hosting" Version="1.0.0-preview.260108.1" />
    <PackageVersion Include="SonarAnalyzer.CSharp" Version="10.22.0.136894" />
    <PackageVersion Include="TUnit" Version="1.29.0" />
  </ItemGroup>
</Project>