<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>XE_Local_AI_Engine.Client.Persistence.Tests</AssemblyName>
    <OutputType>Exe</OutputType>
    <RootNamespace>XE_Local_AI_Engine.Client.Persistence.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage"/>
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport"/>
    <PackageReference Include="Microsoft.Testing.Platform"/>
    <PackageReference Include="NSubstitute"/>
    <PackageReference Include="NSubstitute.Analyzers.CSharp" PrivateAssets="all"/>
    <PackageReference Include="TUnit"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\XE-Local-AI-Engine.Client.Application\XE-Local-AI-Engine.Client.Application.csproj"/>
    <ProjectReference Include="..\XE-Local-AI-Engine.Client.Persistence\XE-Local-AI-Engine.Client.Persistence.csproj"/>
    <ProjectReference Include="..\XE-Local-AI-Engine.Client\XE-Local-AI-Engine.Client.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="NegativeFence/**/*.cs"/>
  </ItemGroup>

</Project>
