// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XE_Local_AI_Engine.Client.Persistence;

#nullable disable

namespace XE_Local_AI_Engine.Client.Persistence.Migrations
{
    [DbContext(typeof(NodeChatDbContext))]
    [Migration("20260527010918_AddNodeChatBranchVariantFeedback")]
    partial class AddNodeChatBranchVariantFeedback
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.NodeConversation", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("conversation_id");

                    b.Property<bool>("Archived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("archived");

                    b.Property<Guid?>("BranchOfConversationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("branch_of_conversation_id");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsPinned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_pinned");

                    b.Property<long>("LastSeenUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_seen_utc");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Local")
                        .HasColumnName("origin");

                    b.Property<bool>("Purged")
                        .HasColumnType("INTEGER")
                        .HasColumnName("purged");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("ConversationId");

                    b.ToTable("conversations", (string)null);
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.NodeMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("message_id");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("content");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("conversation_id");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT")
                        .HasColumnName("error");

                    b.Property<byte[]>("MetadataJson")
                        .HasColumnType("BLOB")
                        .HasColumnName("metadata_json");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Local")
                        .HasColumnName("origin");

                    b.Property<Guid?>("ParentMessageId")
                        .HasColumnType("TEXT")
                        .HasColumnName("parent_message_id");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("TEXT")
                        .HasColumnName("request_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sequence");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("completed")
                        .HasColumnName("status");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("VariantGroupId")
                        .HasColumnType("TEXT")
                        .HasColumnName("variant_group_id");

                    b.HasKey("MessageId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("ParentMessageId");

                    b.HasIndex("RequestId");

                    b.HasIndex("VariantGroupId");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.NodeMessageFeedback", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("TEXT")
                        .HasColumnName("message_id");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT")
                        .HasColumnName("comment");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("conversation_id");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("rating");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("MessageId");

                    b.HasIndex("ConversationId");

                    b.ToTable("message_feedback", (string)null);
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.NodePurgedTombstone", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("conversation_id");

                    b.Property<long?>("AckedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("acked_at_utc");

                    b.Property<long>("PurgedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("purged_at_utc");

                    b.HasKey("ConversationId");

                    b.ToTable("purged_tombstones", (string)null);
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.NodeToolEvent", b =>
                {
                    b.Property<Guid>("ToolCallId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("tool_call_id");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("conversation_id");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc");

                    b.Property<byte[]>("PlaintextArgs")
                        .HasColumnType("BLOB")
                        .HasColumnName("plaintext_args");

                    b.Property<byte[]>("PlaintextResult")
                        .HasColumnType("BLOB")
                        .HasColumnName("plaintext_result");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tool_name");

                    b.HasKey("ToolCallId");

                    b.HasIndex("ConversationId");

                    b.ToTable("tool_events", (string)null);
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.NodeMessage", b =>
                {
                    b.HasOne("XE_Local_AI_Engine.Client.Persistence.Entities.NodeConversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.NodeMessageFeedback", b =>
                {
                    b.HasOne("XE_Local_AI_Engine.Client.Persistence.Entities.NodeMessage", "Message")
                        .WithOne()
                        .HasForeignKey("XE_Local_AI_Engine.Client.Persistence.Entities.NodeMessageFeedback", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.NodeToolEvent", b =>
                {
                    b.HasOne("XE_Local_AI_Engine.Client.Persistence.Entities.NodeConversation", "Conversation")
                        .WithMany("ToolEvents")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.NodeConversation", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("ToolEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
