// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XE_Local_AI_Engine.Client.Persistence;

#nullable disable

namespace XE_Local_AI_Engine.Client.Persistence.Migrations
{
    [DbContext(typeof(NodeChatDbContext))]
    partial class NodeChatDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.AgentDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AllowedSkillIdsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]")
                        .HasColumnName("allowed_skill_ids_json");

                    b.Property<string>("AllowedToolNamesJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("allowed_tool_names_json");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("DefaultTemporaryChat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("default_temporary_chat");

                    b.Property<byte[]>("Description")
                        .HasColumnType("BLOB")
                        .HasColumnName("description");

                    b.Property<byte[]>("Instructions")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("instructions");

                    b.Property<int>("Kind")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("kind");

                    b.Property<bool>("MemoryExtractionEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("memory_extraction_enabled");

                    b.Property<string>("ModelProfile")
                        .HasColumnType("TEXT")
                        .HasColumnName("model_profile");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("OrchestrationTopologyJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("orchestration_topology_json");

                    b.Property<bool>("PlaybookEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("playbook_enabled");

                    b.Property<string>("ReasoningEffort")
                        .HasColumnType("TEXT")
                        .HasColumnName("reasoning_effort");

                    b.Property<string>("SeedSlug")
                        .HasColumnType("TEXT")
                        .HasColumnName("seed_slug");

                    b.Property<int>("Source")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("source");

                    b.Property<string>("ToolApprovalsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tool_approvals_json");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("SeedSlug")
                        .IsUnique()
                        .HasFilter("\"seed_slug\" IS NOT NULL");

                    b.ToTable("agent_definitions", (string)null);
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.AgentExecutionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("AgentDefinitionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_definition_id");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("completion_tokens");

                    b.Property<string>("ConfigHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("config_hash");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("conversation_id");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ErrorClass")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_class");

                    b.Property<long>("LatencyMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("latency_ms");

                    b.Property<Guid?>("MessageId")
                        .HasColumnType("TEXT")
                        .HasColumnName("message_id");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("model_name");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("prompt_tokens");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER")
                        .HasColumnName("success");

                    b.HasKey("Id");

                    b.HasIndex("AgentDefinitionId", "CreatedAtUtc");

                    b.ToTable("agent_execution_logs", (string)null);
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.AgentSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("body");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc");

                    b.Property<byte[]>("Description")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("description");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .UseCollation("NOCASE");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("agent_skills", (string)null);
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.ApprovedUtilityImage", b =>
                {
                    b.Property<string>("ApprovedImageId")
                        .HasColumnType("TEXT")
                        .HasColumnName("approved_image_id")
                        .UseCollation("NOCASE");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc");

                    b.Property<long?>("DeprecatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deprecated_at_utc");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("DiagnosticsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("diagnostics_json");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<string>("ImageReference")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("image_reference");

                    b.Property<long?>("LastSuccessfulRunAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_successful_run_at_utc");

                    b.Property<long?>("LastUsedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_used_at_utc");

                    b.Property<int>("Purpose")
                        .HasColumnType("INTEGER")
                        .HasColumnName("purpose");

                    b.Property<string>("ReplacementApprovedImageId")
                        .HasColumnType("TEXT")
                        .HasColumnName("replacement_approved_image_id");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_url");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpstreamVersion")
                        .HasColumnType("TEXT")
                        .HasColumnName("upstream_version");

                    b.HasKey("ApprovedImageId");

                    b.ToTable("approved_utility_images", (string)null);
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.CanvasWorkflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc");

                    b.Property<byte[]>("GraphJson")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("graph_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("canvas_workflows", (string)null);
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.ConversationUploadedFile", b =>
                {
                    b.Property<Guid>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("file_id");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("conversation_id");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("extension");

                    b.Property<int?>("ExtractedChars")
                        .HasColumnType("INTEGER")
                        .HasColumnName("extracted_chars");

                    b.Property<string>("ExtractionStatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("extraction_status");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("mime_type");

                    b.Property<byte[]>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("original_file_name");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("storage_path");

                    b.HasKey("FileId");

                    b.HasIndex("ConversationId");

                    b.ToTable("conversation_uploaded_files", (string)null);
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.GeneratedImage", b =>
                {
                    b.Property<Guid>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("image_id");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER")
                        .HasColumnName("height");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT")
                        .HasColumnName("job_id");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("mime_type");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("storage_path");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER")
                        .HasColumnName("width");

                    b.HasKey("ImageId");

                    b.HasIndex("JobId");

                    b.ToTable("generated_images", (string)null);
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.GoldenConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("AgentDefinitionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_definition_id");

                    b.Property<byte[]>("Assertion")
                        .HasColumnType("BLOB")
                        .HasColumnName("assertion");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<byte[]>("InputTurns")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("input_turns");

                    b.Property<byte[]>("Rubric")
                        .HasColumnType("BLOB")
                        .HasColumnName("rubric");

                    b.Property<int>("Source")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("source");

                    b.Property<Guid?>("SourceConversationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_conversation_id");

                    b.Property<Guid?>("SourceMessageId")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_message_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("AgentDefinitionId");

                    b.ToTable("golden_conversations", (string)null);
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.ImageJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long?>("CancellationRequestedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cancellation_requested_at_utc");

                    b.Property<double>("CfgScale")
                        .HasColumnType("REAL")
                        .HasColumnName("cfg_scale");

                    b.Property<long?>("CompletedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("completed_at_utc");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_ms");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER")
                        .HasColumnName("height");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("TEXT")
                        .HasColumnName("image_id");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("model_name");

                    b.Property<byte[]>("NegativePrompt")
                        .HasColumnType("BLOB")
                        .HasColumnName("negative_prompt");

                    b.Property<byte[]>("Prompt")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("prompt");

                    b.Property<string>("Sampler")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("sampler");

                    b.Property<string>("SanitizedError")
                        .HasColumnType("TEXT")
                        .HasColumnName("sanitized_error");

                    b.Property<long>("Seed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("seed");

                    b.Property<long?>("StartedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("started_at_utc");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<int>("Steps")
                        .HasColumnType("INTEGER")
                        .HasColumnName("steps");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("Status");

                    b.ToTable("image_jobs", (string)null);
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.ImageModelProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Backend")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("backend");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc");

                    b.Property<double>("DefaultCfg")
                        .HasColumnType("REAL")
                        .HasColumnName("default_cfg");

                    b.Property<int>("DefaultHeight")
                        .HasColumnType("INTEGER")
                        .HasColumnName("default_height");

                    b.Property<string>("DefaultSampler")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("default_sampler");

                    b.Property<int>("DefaultSteps")
                        .HasColumnType("INTEGER")
                        .HasColumnName("default_steps");

                    b.Property<int>("DefaultWidth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("default_width");

                    b.Property<string>("MachineKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("machine_key");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("model_name");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("MachineKey", "ModelName", "Backend")
                        .IsUnique();

                    b.ToTable("image_model_profiles", (string)null);
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.InferenceProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Backend")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("backend");

                    b.Property<Guid?>("BenchmarkSnapshotId")
                        .HasColumnType("TEXT")
                        .HasColumnName("benchmark_snapshot_id");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("CtxSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ctx_size");

                    b.Property<int?>("ExpertCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("expert_count");

                    b.Property<bool>("FlashAttn")
                        .HasColumnType("INTEGER")
                        .HasColumnName("flash_attn");

                    b.Property<long?>("FreeVramAtFreezeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("free_vram_at_freeze_bytes");

                    b.Property<bool>("IsMoe")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_moe");

                    b.Property<string>("KvTypeK")
                        .HasColumnType("TEXT")
                        .HasColumnName("kv_type_k");

                    b.Property<string>("KvTypeV")
                        .HasColumnType("TEXT")
                        .HasColumnName("kv_type_v");

                    b.Property<string>("LlamacppBuild")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("llamacpp_build");

                    b.Property<string>("MachineKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("machine_key");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("model_name");

                    b.Property<int?>("NGpuLayers")
                        .HasColumnType("INTEGER")
                        .HasColumnName("n_gpu_layers");

                    b.Property<long?>("NParams")
                        .HasColumnType("INTEGER")
                        .HasColumnName("n_params");

                    b.Property<string>("OverrideTensor")
                        .HasColumnType("TEXT")
                        .HasColumnName("override_tensor");

                    b.Property<string>("Quant")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("quant");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER")
                        .HasColumnName("role");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<string>("TensorSplit")
                        .HasColumnType("TEXT")
                        .HasColumnName("tensor_split");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("MachineKey", "ModelName", "Role", "Backend")
                        .IsUnique();

                    b.ToTable("inference_profiles", (string)null);
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.KnowledgeChunkVector", b =>
                {
                    b.Property<Guid>("ChunkId")
                        .HasColumnType("TEXT")
                        .HasColumnName("chunk_id");

                    b.Property<int>("Dim")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dim");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("document_id");

                    b.Property<byte[]>("Embedding")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("embedding");

                    b.Property<string>("EmbeddingModel")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("embedding_model");

                    b.HasKey("ChunkId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("EmbeddingModel");

                    b.ToTable("knowledge_chunk_vectors", (string)null);
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.KnowledgeDocument", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("document_id");

                    b.Property<int>("ChunkCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("chunk_count");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content_hash");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("EmbeddingModel")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("embedding_model");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("extension");

                    b.Property<string>("FailureReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("failure_reason");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("mime_type");

                    b.Property<byte[]>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("original_file_name");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("storage_path");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("DocumentId");

                    b.HasIndex("ContentHash")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("knowledge_documents", (string)null);
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.KnowledgeDocumentChunk", b =>
                {
                    b.Property<long>("Rowid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("rowid");

                    b.Property<Guid>("ChunkId")
                        .HasColumnType("TEXT")
                        .HasColumnName("chunk_id");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("chunk_index");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("document_id");

                    b.Property<string>("HeadingPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("heading_path");

                    b.Property<Guid?>("SectionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("section_id");

                    b.Property<int>("TokenCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("token_count");

                    b.HasKey("Rowid");

                    b.HasIndex("SectionId");

                    b.HasIndex("DocumentId", "ChunkIndex");

                    b.ToTable("knowledge_document_chunks", (string)null);
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.KnowledgeDocumentSection", b =>
                {
                    b.Property<Guid>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("section_id");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("document_id");

                    b.Property<string>("Heading")
                        .HasColumnType("TEXT")
                        .HasColumnName("heading");

                    b.Property<int?>("Level")
                        .HasColumnType("INTEGER")
                        .HasColumnName("level");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ordinal");

                    b.HasKey("SectionId");

                    b.HasIndex("DocumentId", "Ordinal");

                    b.ToTable("knowledge_document_sections", (string)null);
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.McpServerRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<byte[]>("ArgumentsJson")
                        .HasColumnType("BLOB")
                        .HasColumnName("arguments");

                    b.Property<string>("Command")
                        .HasColumnType("TEXT")
                        .HasColumnName("command");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc");

                    b.Property<byte[]>("Description")
                        .HasColumnType("BLOB")
                        .HasColumnName("description");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<byte[]>("EnvJson")
                        .HasColumnType("BLOB")
                        .HasColumnName("env");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .UseCollation("NOCASE");

                    b.Property<int>("TransportKind")
                        .HasColumnType("INTEGER")
                        .HasColumnName("transport_kind");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT")
                        .HasColumnName("url");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.Property<string>("WorkingDirectory")
                        .HasColumnType("TEXT")
                        .HasColumnName("working_directory");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("mcp_servers", (string)null);
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.ModelClassification", b =>
                {
                    b.Property<string>("ModelName")
                        .HasColumnType("TEXT")
                        .HasColumnName("model_name")
                        .UseCollation("NOCASE");

                    b.Property<long?>("DetectedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("detected_at_utc");

                    b.Property<string>("DetectedCapabilitiesJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("detected_capabilities_json");

                    b.Property<int>("DetectedKind")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("detected_kind");

                    b.Property<string>("Digest")
                        .HasColumnType("TEXT")
                        .HasColumnName("digest");

                    b.Property<int?>("OverrideKind")
                        .HasColumnType("INTEGER")
                        .HasColumnName("override_kind");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("ModelName");

                    b.ToTable("model_classifications", (string)null);
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.ModelFitBenchmark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Backend")
                        .HasColumnType("TEXT")
                        .HasColumnName("backend");

                    b.Property<double?>("CacheHitRate")
                        .HasColumnType("REAL")
                        .HasColumnName("cache_hit_rate");

                    b.Property<int?>("CtxSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ctx_size");

                    b.Property<byte[]>("DiagnosticsJson")
                        .HasColumnType("BLOB")
                        .HasColumnName("diagnostics_json");

                    b.Property<string>("KvType")
                        .HasColumnType("TEXT")
                        .HasColumnName("kv_type");

                    b.Property<string>("LlamacppBuild")
                        .HasColumnType("TEXT")
                        .HasColumnName("llamacpp_build");

                    b.Property<string>("MachineKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("machine_key");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("model_name");

                    b.Property<int?>("NGpuLayers")
                        .HasColumnType("INTEGER")
                        .HasColumnName("n_gpu_layers");

                    b.Property<string>("OverrideTensor")
                        .HasColumnType("TEXT")
                        .HasColumnName("override_tensor");

                    b.Property<double?>("PpTokensPerSecond")
                        .HasColumnType("REAL")
                        .HasColumnName("pp_tokens_per_second");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_name");

                    b.Property<string>("Quant")
                        .HasColumnType("TEXT")
                        .HasColumnName("quant");

                    b.Property<byte[]>("RawJson")
                        .HasColumnType("BLOB")
                        .HasColumnName("raw_json");

                    b.Property<int?>("Runs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("runs");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("TEXT")
                        .HasColumnName("snapshot_id");

                    b.Property<string>("TensorSplit")
                        .HasColumnType("TEXT")
                        .HasColumnName("tensor_split");

                    b.Property<double?>("TokensPerSecond")
                        .HasColumnType("REAL")
                        .HasColumnName("tokens_per_second");

                    b.Property<double?>("ToolLoopMs")
                        .HasColumnType("REAL")
                        .HasColumnName("tool_loop_ms");

                    b.Property<double?>("TotalLatencyMs")
                        .HasColumnType("REAL")
                        .HasColumnName("total_latency_ms");

                    b.Property<double?>("TtftMs")
                        .HasColumnType("REAL")
                        .HasColumnName("ttft_ms");

                    b.Property<long?>("VramAfterBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("vram_after_bytes");

                    b.Property<long?>("VramLoadBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("vram_load_bytes");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId");

                    b.ToTable("model_fit_benchmarks", (string)null);
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.ModelFitRecommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int?>("ContextTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("context_tokens");

                    b.Property<string>("DiagnosticsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("diagnostics_json");

                    b.Property<double?>("EstimatedTokensPerSecond")
                        .HasColumnType("REAL")
                        .HasColumnName("estimated_tokens_per_second");

                    b.Property<string>("FitLevel")
                        .HasColumnType("TEXT")
                        .HasColumnName("fit_level");

                    b.Property<bool>("IsInstalled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_installed");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("model_name");

                    b.Property<string>("ProviderModelName")
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_model_name");

                    b.Property<string>("PullModelName")
                        .HasColumnType("TEXT")
                        .HasColumnName("pull_model_name");

                    b.Property<string>("Quantization")
                        .HasColumnType("TEXT")
                        .HasColumnName("quantization");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rank");

                    b.Property<double?>("RequiredRamMb")
                        .HasColumnType("REAL")
                        .HasColumnName("required_ram_mb");

                    b.Property<double?>("RequiredVramMb")
                        .HasColumnType("REAL")
                        .HasColumnName("required_vram_mb");

                    b.Property<string>("RunMode")
                        .HasColumnType("TEXT")
                        .HasColumnName("run_mode");

                    b.Property<double>("Score")
                        .HasColumnType("REAL")
                        .HasColumnName("score");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("TEXT")
                        .HasColumnName("snapshot_id");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId", "Rank");

                    b.ToTable("model_fit_recommendations", (string)null);
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.ModelFitSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ApprovedImageId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("approved_image_id");

                    b.Property<long?>("CompletedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("completed_at_utc");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByRunId")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_run_id");

                    b.Property<byte[]>("DiagnosticsJson")
                        .HasColumnType("BLOB")
                        .HasColumnName("diagnostics_json");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_ms");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("exit_code");

                    b.Property<bool>("IsLatestSuccessful")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_latest_successful");

                    b.Property<string>("ModelName")
                        .HasColumnType("TEXT")
                        .HasColumnName("model_name");

                    b.Property<int>("Operation")
                        .HasColumnType("INTEGER")
                        .HasColumnName("operation");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_name");

                    b.Property<byte[]>("RawJson")
                        .HasColumnType("BLOB")
                        .HasColumnName("raw_json");

                    b.Property<long?>("StartedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("started_at_utc");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<byte[]>("StderrExcerpt")
                        .HasColumnType("BLOB")
                        .HasColumnName("stderr_excerpt");

                    b.Property<string>("UseCase")
                        .HasColumnType("TEXT")
                        .HasColumnName("use_case");

                    b.HasKey("Id");

                    b.HasIndex("Operation", "UseCase", "ProviderName", "ModelName", "IsLatestSuccessful");

                    b.ToTable("model_fit_snapshots", (string)null);
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.ModelProviderMap", b =>
                {
                    b.Property<string>("ModelName")
                        .HasColumnType("TEXT")
                        .HasColumnName("model_name")
                        .UseCollation("NOCASE");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_name");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("ModelName");

                    b.ToTable("model_provider_map", (string)null);
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.NodeConversation", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("conversation_id");

                    b.Property<Guid?>("AgentDefinitionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_definition_id");

                    b.Property<bool>("Archived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("archived");

                    b.Property<Guid?>("BranchOfConversationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("branch_of_conversation_id");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsPinned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_pinned");

                    b.Property<long>("LastSeenUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_seen_utc");

                    b.Property<bool>("MemoryExcluded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("memory_excluded");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Local")
                        .HasColumnName("origin");

                    b.Property<bool>("Purged")
                        .HasColumnType("INTEGER")
                        .HasColumnName("purged");

                    b.Property<string>("SelectedPathJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("selected_path_json");

                    b.Property<byte[]>("Title")
                        .HasColumnType("BLOB")
                        .HasColumnName("title");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("ConversationId");

                    b.ToTable("conversations", (string)null);
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.NodeMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("message_id");

                    b.Property<Guid?>("AgentDefinitionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_definition_id");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("content");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("conversation_id");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT")
                        .HasColumnName("error");

                    b.Property<byte[]>("MetadataJson")
                        .HasColumnType("BLOB")
                        .HasColumnName("metadata_json");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Local")
                        .HasColumnName("origin");

                    b.Property<Guid?>("ParentMessageId")
                        .HasColumnType("TEXT")
                        .HasColumnName("parent_message_id");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("TEXT")
                        .HasColumnName("request_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sequence");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("completed")
                        .HasColumnName("status");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("VariantGroupId")
                        .HasColumnType("TEXT")
                        .HasColumnName("variant_group_id");

                    b.HasKey("MessageId");

                    b.HasIndex("AgentDefinitionId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("ParentMessageId");

                    b.HasIndex("RequestId");

                    b.HasIndex("VariantGroupId");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.NodeMessageFeedback", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("TEXT")
                        .HasColumnName("message_id");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT")
                        .HasColumnName("comment");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("conversation_id");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("rating");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("MessageId");

                    b.HasIndex("ConversationId");

                    b.ToTable("message_feedback", (string)null);
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.NodePurgedTombstone", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("conversation_id");

                    b.Property<long?>("AckedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("acked_at_utc");

                    b.Property<long>("PurgedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("purged_at_utc");

                    b.HasKey("ConversationId");

                    b.ToTable("purged_tombstones", (string)null);
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.NodeSelectedFolder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("alias");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc");

                    b.Property<byte[]>("HostPath")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("host_path");

                    b.Property<int>("Mode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("mode");

                    b.HasKey("Id");

                    b.HasIndex("Alias")
                        .IsUnique();

                    b.ToTable("selected_folders", (string)null);
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.NodeToolEvent", b =>
                {
                    b.Property<Guid>("ToolCallId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("tool_call_id");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("conversation_id");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc");

                    b.Property<byte[]>("PlaintextArgs")
                        .HasColumnType("BLOB")
                        .HasColumnName("plaintext_args");

                    b.Property<byte[]>("PlaintextResult")
                        .HasColumnType("BLOB")
                        .HasColumnName("plaintext_result");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tool_name");

                    b.HasKey("ToolCallId");

                    b.HasIndex("ConversationId");

                    b.ToTable("tool_events", (string)null);
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.PlaybookAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("AgentDefinitionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_definition_id");

                    b.Property<byte[]>("Behavior")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("behavior");

                    b.Property<double?>("Confidence")
                        .HasColumnType("REAL")
                        .HasColumnName("confidence");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc");

                    b.Property<long?>("EnabledAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled_at_utc");

                    b.Property<string>("EvalResult")
                        .HasColumnType("TEXT")
                        .HasColumnName("eval_result");

                    b.Property<int?>("MemoryScope")
                        .HasColumnType("INTEGER")
                        .HasColumnName("memory_scope");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("priority");

                    b.Property<string>("Scope")
                        .HasColumnType("TEXT")
                        .HasColumnName("scope");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER")
                        .HasColumnName("source");

                    b.Property<string>("SourceFeedbackIds")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_feedback_ids");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER")
                        .HasColumnName("state");

                    b.Property<byte[]>("TriggerCondition")
                        .HasColumnType("BLOB")
                        .HasColumnName("trigger_condition");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("AgentDefinitionId");

                    b.ToTable("playbook_actions", (string)null);
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.ScheduledJobDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_by");

                    b.Property<string>("CronExpression")
                        .HasColumnType("TEXT")
                        .HasColumnName("cron_expression");

                    b.Property<long?>("DeletedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<long?>("DisabledAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("disabled_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<long?>("EndAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("end_at_utc");

                    b.Property<long?>("IntervalSeconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("interval_seconds");

                    b.Property<int?>("MaxRuntimeSeconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_runtime_seconds");

                    b.Property<int>("MisfirePolicy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("misfire_policy");

                    b.Property<byte[]>("ParameterJson")
                        .HasColumnType("BLOB")
                        .HasColumnName("parameter_json");

                    b.Property<bool>("PreventOverlap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("prevent_overlap");

                    b.Property<int?>("RepeatCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("repeat_count");

                    b.Property<int>("ScheduleKind")
                        .HasColumnType("INTEGER")
                        .HasColumnName("schedule_kind");

                    b.Property<long?>("StartAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("start_at_utc");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("template_id");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("UTC")
                        .HasColumnName("time_zone_id");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId", "Enabled");

                    b.ToTable("scheduled_job_definitions", (string)null);
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.ScheduledJobRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long?>("ActualFireTimeUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("actual_fire_time_utc");

                    b.Property<long?>("CancellationRequestedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cancellation_requested_at_utc");

                    b.Property<long?>("CompletedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("completed_at_utc");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc");

                    b.Property<byte[]>("DetailsJson")
                        .HasColumnType("BLOB")
                        .HasColumnName("details_json");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_details");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<string>("QuartzFireInstanceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("quartz_fire_instance_id");

                    b.Property<long?>("ScheduledFireTimeUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("scheduled_fire_time_utc");

                    b.Property<Guid>("ScheduledJobId")
                        .HasColumnType("TEXT")
                        .HasColumnName("scheduled_job_id");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT")
                        .HasColumnName("summary");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("template_id");

                    b.Property<int>("TriggeredBy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("triggered_by");

                    b.HasKey("Id");

                    b.HasIndex("QuartzFireInstanceId")
                        .IsUnique()
                        .HasFilter("quartz_fire_instance_id IS NOT NULL");

                    b.HasIndex("ScheduledJobId", "ActualFireTimeUtc");

                    b.ToTable("scheduled_job_runs", (string)null);
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.ScheduledJobRunEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<byte[]>("DataJson")
                        .HasColumnType("BLOB")
                        .HasColumnName("data_json");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.Property<long>("OccurredAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT")
                        .HasColumnName("run_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sequence");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "Sequence")
                        .IsUnique();

                    b.ToTable("scheduled_job_run_events", (string)null);
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.ConversationUploadedFile", b =>
                {
                    b.HasOne("XE_Local_AI_Engine.Client.Persistence.Entities.NodeConversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.GeneratedImage", b =>
                {
                    b.HasOne("XE_Local_AI_Engine.Client.Persistence.Entities.ImageJob", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.GoldenConversation", b =>
                {
                    b.HasOne("XE_Local_AI_Engine.Client.Persistence.Entities.AgentDefinition", null)
                        .WithMany()
                        .HasForeignKey("AgentDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.KnowledgeChunkVector", b =>
                {
                    b.HasOne("XE_Local_AI_Engine.Client.Persistence.Entities.KnowledgeDocumentChunk", null)
                        .WithOne()
                        .HasForeignKey("XE_Local_AI_Engine.Client.Persistence.Entities.KnowledgeChunkVector", "ChunkId")
                        .HasPrincipalKey("XE_Local_AI_Engine.Client.Persistence.Entities.KnowledgeDocumentChunk", "ChunkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XE_Local_AI_Engine.Client.Persistence.Entities.KnowledgeDocument", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.KnowledgeDocumentChunk", b =>
                {
                    b.HasOne("XE_Local_AI_Engine.Client.Persistence.Entities.KnowledgeDocument", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XE_Local_AI_Engine.Client.Persistence.Entities.KnowledgeDocumentSection", null)
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.KnowledgeDocumentSection", b =>
                {
                    b.HasOne("XE_Local_AI_Engine.Client.Persistence.Entities.KnowledgeDocument", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.ModelFitBenchmark", b =>
                {
                    b.HasOne("XE_Local_AI_Engine.Client.Persistence.Entities.ModelFitSnapshot", null)
                        .WithMany()
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.ModelFitRecommendation", b =>
                {
                    b.HasOne("XE_Local_AI_Engine.Client.Persistence.Entities.ModelFitSnapshot", null)
                        .WithMany()
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.NodeMessage", b =>
                {
                    b.HasOne("XE_Local_AI_Engine.Client.Persistence.Entities.NodeConversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.NodeMessageFeedback", b =>
                {
                    b.HasOne("XE_Local_AI_Engine.Client.Persistence.Entities.NodeMessage", "Message")
                        .WithOne()
                        .HasForeignKey("XE_Local_AI_Engine.Client.Persistence.Entities.NodeMessageFeedback", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.NodeToolEvent", b =>
                {
                    b.HasOne("XE_Local_AI_Engine.Client.Persistence.Entities.NodeConversation", "Conversation")
                        .WithMany("ToolEvents")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.PlaybookAction", b =>
                {
                    b.HasOne("XE_Local_AI_Engine.Client.Persistence.Entities.AgentDefinition", null)
                        .WithMany()
                        .HasForeignKey("AgentDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.ScheduledJobRunEvent", b =>
                {
                    b.HasOne("XE_Local_AI_Engine.Client.Persistence.Entities.ScheduledJobRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.NodeConversation", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("ToolEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
