// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XE_Local_AI_Engine.Client.Persistence;

#nullable disable

namespace XE_Local_AI_Engine.Client.Persistence.Migrations
{
    [DbContext(typeof(NodeChatDbContext))]
    partial class NodeChatDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.AgentDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AllowedToolNamesJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("allowed_tool_names_json");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc");

                    b.Property<byte[]>("Description")
                        .HasColumnType("BLOB")
                        .HasColumnName("description");

                    b.Property<byte[]>("Instructions")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("instructions");

                    b.Property<int>("Kind")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("kind");

                    b.Property<string>("ModelProfile")
                        .HasColumnType("TEXT")
                        .HasColumnName("model_profile");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("OrchestrationTopologyJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("orchestration_topology_json");

                    b.Property<bool>("PlaybookEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("playbook_enabled");

                    b.Property<string>("ReasoningEffort")
                        .HasColumnType("TEXT")
                        .HasColumnName("reasoning_effort");

                    b.Property<string>("ToolApprovalsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tool_approvals_json");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("agent_definitions", (string)null);
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.GoldenConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("AgentDefinitionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_definition_id");

                    b.Property<byte[]>("Assertion")
                        .HasColumnType("BLOB")
                        .HasColumnName("assertion");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<byte[]>("InputTurns")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("input_turns");

                    b.Property<byte[]>("Rubric")
                        .HasColumnType("BLOB")
                        .HasColumnName("rubric");

                    b.Property<int>("Source")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("source");

                    b.Property<Guid?>("SourceConversationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_conversation_id");

                    b.Property<Guid?>("SourceMessageId")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_message_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("AgentDefinitionId");

                    b.ToTable("golden_conversations", (string)null);
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.McpServerRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<byte[]>("ArgumentsJson")
                        .HasColumnType("BLOB")
                        .HasColumnName("arguments");

                    b.Property<string>("Command")
                        .HasColumnType("TEXT")
                        .HasColumnName("command");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc");

                    b.Property<byte[]>("Description")
                        .HasColumnType("BLOB")
                        .HasColumnName("description");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<byte[]>("EnvJson")
                        .HasColumnType("BLOB")
                        .HasColumnName("env");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .UseCollation("NOCASE");

                    b.Property<int>("TransportKind")
                        .HasColumnType("INTEGER")
                        .HasColumnName("transport_kind");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT")
                        .HasColumnName("url");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.Property<string>("WorkingDirectory")
                        .HasColumnType("TEXT")
                        .HasColumnName("working_directory");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("mcp_servers", (string)null);
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.NodeConversation", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("conversation_id");

                    b.Property<Guid?>("AgentDefinitionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_definition_id");

                    b.Property<bool>("Archived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("archived");

                    b.Property<Guid?>("BranchOfConversationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("branch_of_conversation_id");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsPinned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_pinned");

                    b.Property<long>("LastSeenUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_seen_utc");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Local")
                        .HasColumnName("origin");

                    b.Property<bool>("Purged")
                        .HasColumnType("INTEGER")
                        .HasColumnName("purged");

                    b.Property<string>("SelectedPathJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("selected_path_json");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("ConversationId");

                    b.ToTable("conversations", (string)null);
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.NodeMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("message_id");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("content");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("conversation_id");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT")
                        .HasColumnName("error");

                    b.Property<byte[]>("MetadataJson")
                        .HasColumnType("BLOB")
                        .HasColumnName("metadata_json");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Local")
                        .HasColumnName("origin");

                    b.Property<Guid?>("ParentMessageId")
                        .HasColumnType("TEXT")
                        .HasColumnName("parent_message_id");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("TEXT")
                        .HasColumnName("request_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sequence");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("completed")
                        .HasColumnName("status");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("VariantGroupId")
                        .HasColumnType("TEXT")
                        .HasColumnName("variant_group_id");

                    b.HasKey("MessageId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("ParentMessageId");

                    b.HasIndex("RequestId");

                    b.HasIndex("VariantGroupId");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.NodeMessageFeedback", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("TEXT")
                        .HasColumnName("message_id");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT")
                        .HasColumnName("comment");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("conversation_id");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("rating");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("MessageId");

                    b.HasIndex("ConversationId");

                    b.ToTable("message_feedback", (string)null);
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.NodePurgedTombstone", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("conversation_id");

                    b.Property<long?>("AckedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("acked_at_utc");

                    b.Property<long>("PurgedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("purged_at_utc");

                    b.HasKey("ConversationId");

                    b.ToTable("purged_tombstones", (string)null);
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.NodeSelectedFolder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("alias");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc");

                    b.Property<byte[]>("HostPath")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("host_path");

                    b.Property<int>("Mode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("mode");

                    b.HasKey("Id");

                    b.HasIndex("Alias")
                        .IsUnique();

                    b.ToTable("selected_folders", (string)null);
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.NodeToolEvent", b =>
                {
                    b.Property<Guid>("ToolCallId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("tool_call_id");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("conversation_id");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc");

                    b.Property<byte[]>("PlaintextArgs")
                        .HasColumnType("BLOB")
                        .HasColumnName("plaintext_args");

                    b.Property<byte[]>("PlaintextResult")
                        .HasColumnType("BLOB")
                        .HasColumnName("plaintext_result");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tool_name");

                    b.HasKey("ToolCallId");

                    b.HasIndex("ConversationId");

                    b.ToTable("tool_events", (string)null);
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.PlaybookAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("AgentDefinitionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_definition_id");

                    b.Property<byte[]>("Behavior")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("behavior");

                    b.Property<double?>("Confidence")
                        .HasColumnType("REAL")
                        .HasColumnName("confidence");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc");

                    b.Property<long?>("EnabledAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled_at_utc");

                    b.Property<string>("EvalResult")
                        .HasColumnType("TEXT")
                        .HasColumnName("eval_result");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("priority");

                    b.Property<string>("Scope")
                        .HasColumnType("TEXT")
                        .HasColumnName("scope");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER")
                        .HasColumnName("source");

                    b.Property<string>("SourceFeedbackIds")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_feedback_ids");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER")
                        .HasColumnName("state");

                    b.Property<byte[]>("TriggerCondition")
                        .HasColumnType("BLOB")
                        .HasColumnName("trigger_condition");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("AgentDefinitionId");

                    b.ToTable("playbook_actions", (string)null);
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.ScheduledJobDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_by");

                    b.Property<string>("CronExpression")
                        .HasColumnType("TEXT")
                        .HasColumnName("cron_expression");

                    b.Property<long?>("DeletedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<long?>("DisabledAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("disabled_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<long?>("EndAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("end_at_utc");

                    b.Property<long?>("IntervalSeconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("interval_seconds");

                    b.Property<int?>("MaxRuntimeSeconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_runtime_seconds");

                    b.Property<int>("MisfirePolicy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("misfire_policy");

                    b.Property<byte[]>("ParameterJson")
                        .HasColumnType("BLOB")
                        .HasColumnName("parameter_json");

                    b.Property<bool>("PreventOverlap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("prevent_overlap");

                    b.Property<int?>("RepeatCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("repeat_count");

                    b.Property<int>("ScheduleKind")
                        .HasColumnType("INTEGER")
                        .HasColumnName("schedule_kind");

                    b.Property<long?>("StartAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("start_at_utc");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("template_id");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("UTC")
                        .HasColumnName("time_zone_id");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId", "Enabled");

                    b.ToTable("scheduled_job_definitions", (string)null);
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.ScheduledJobRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long?>("ActualFireTimeUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("actual_fire_time_utc");

                    b.Property<long?>("CancellationRequestedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cancellation_requested_at_utc");

                    b.Property<long?>("CompletedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("completed_at_utc");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc");

                    b.Property<byte[]>("DetailsJson")
                        .HasColumnType("BLOB")
                        .HasColumnName("details_json");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_details");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<string>("QuartzFireInstanceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("quartz_fire_instance_id");

                    b.Property<long?>("ScheduledFireTimeUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("scheduled_fire_time_utc");

                    b.Property<Guid>("ScheduledJobId")
                        .HasColumnType("TEXT")
                        .HasColumnName("scheduled_job_id");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT")
                        .HasColumnName("summary");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("template_id");

                    b.Property<int>("TriggeredBy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("triggered_by");

                    b.HasKey("Id");

                    b.HasIndex("QuartzFireInstanceId")
                        .IsUnique()
                        .HasFilter("quartz_fire_instance_id IS NOT NULL");

                    b.HasIndex("ScheduledJobId", "ActualFireTimeUtc");

                    b.ToTable("scheduled_job_runs", (string)null);
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.ScheduledJobRunEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<byte[]>("DataJson")
                        .HasColumnType("BLOB")
                        .HasColumnName("data_json");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.Property<long>("OccurredAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT")
                        .HasColumnName("run_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sequence");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "Sequence")
                        .IsUnique();

                    b.ToTable("scheduled_job_run_events", (string)null);
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.GoldenConversation", b =>
                {
                    b.HasOne("XE_Local_AI_Engine.Client.Persistence.Entities.AgentDefinition", null)
                        .WithMany()
                        .HasForeignKey("AgentDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.NodeMessage", b =>
                {
                    b.HasOne("XE_Local_AI_Engine.Client.Persistence.Entities.NodeConversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.NodeMessageFeedback", b =>
                {
                    b.HasOne("XE_Local_AI_Engine.Client.Persistence.Entities.NodeMessage", "Message")
                        .WithOne()
                        .HasForeignKey("XE_Local_AI_Engine.Client.Persistence.Entities.NodeMessageFeedback", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.NodeToolEvent", b =>
                {
                    b.HasOne("XE_Local_AI_Engine.Client.Persistence.Entities.NodeConversation", "Conversation")
                        .WithMany("ToolEvents")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.PlaybookAction", b =>
                {
                    b.HasOne("XE_Local_AI_Engine.Client.Persistence.Entities.AgentDefinition", null)
                        .WithMany()
                        .HasForeignKey("AgentDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.ScheduledJobRunEvent", b =>
                {
                    b.HasOne("XE_Local_AI_Engine.Client.Persistence.Entities.ScheduledJobRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XE_Local_AI_Engine.Client.Persistence.Entities.NodeConversation", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("ToolEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
