namespace XE_Local_AI_Engine.AI.Agent.PreviewWorkflows.Implementation;

using Microsoft.Agents.AI;
using Microsoft.Agents.AI.Workflows;
using Microsoft.Extensions.AI;
using Microsoft.Extensions.Logging;

/// <summary>
///     MAF-native implementation of <see cref="IPreviewWorkflowRunner" />. Builds a raw <see cref="WorkflowBuilder" />
///     from a <see cref="PreviewWorkflowDefinition" /> (Start → Agent → transform → Agent → Debug/Pause → End), resolving
///     each agent node's caller-supplied node-local <see cref="IChatClient" /> by its model id (invariant: each agent
///     runs on its own node-local client) and runs it via <see cref="InProcessExecution.RunStreamingAsync" />. All MAF
///     types are confined to this class + the session (invariant: no Microsoft.Agents.AI types leak out). Linearity
///     (in/out-degree ≤ 1) is enforced by the definition validator before this runs; the runner trusts a linear
///     definition and walks it as an ordered chain.
/// </summary>
internal sealed class PreviewWorkflowRunner : IPreviewWorkflowRunner
{
    private const string StartExecutorId = "preview-start";
    private const string EndExecutorId = "preview-end";
    private readonly ILogger<PreviewWorkflowRunner> _logger;

    private readonly ILoggerFactory _loggerFactory;
    private readonly IServiceProvider _serviceProvider;

    public PreviewWorkflowRunner(ILoggerFactory loggerFactory, IServiceProvider serviceProvider)
    {
        _loggerFactory = loggerFactory ?? throw new ArgumentNullException(nameof(loggerFactory));
        _logger = _loggerFactory.CreateLogger<PreviewWorkflowRunner>();
        _serviceProvider = serviceProvider ?? throw new ArgumentNullException(nameof(serviceProvider));
    }

    public async Task<IPreviewWorkflowRunSession> StartAsync(PreviewWorkflowDefinition definition,
        Func<string, IChatClient> resolveChatClient,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(definition);
        ArgumentNullException.ThrowIfNull(resolveChatClient);
        cancellationToken.ThrowIfCancellationRequested();

        var ordered = OrderLinearChain(definition);

        // Pass 1 — build the executor (and its MAF executor id) for every NON-Start node. Agent executor ids are
        // autogenerated by ChatClientAgent (e.g. "alpha_<guid>"), so they must be captured here before the Start and
        // transform executors can target them. Start is built in pass 2 once the first real node's id is known.
        var agentExecutorIdToNodeId = new Dictionary<string, string>(StringComparer.Ordinal);
        var debugExecutorIdToNodeId = new Dictionary<string, string>(StringComparer.Ordinal);
        var requestPortIdToNodeId = new Dictionary<string, string>(StringComparer.Ordinal);

        var plans = new List<NodePlan>();
        foreach (var node in ordered)
        {
            switch (node.Kind)
            {
                case PreviewNodeKind.Start:
                    plans.Add(new NodePlan(node.Kind, node.Id, StartExecutorId, Binding: null));
                    break;

                case PreviewNodeKind.Agent:
                    {
                        var agentNode = (PreviewAgentNode)node;

                        // Resolve THIS agent's node-local client by its own model id. The caller returns one
                        // shared client per distinct model, so two agents on the same model share a client while an agent on
                        // a different model gets its own — each agent runs on the model the operator selected for it.
                        var agentClient = resolveChatClient(agentNode.ModelId)
                                          ?? throw new InvalidOperationException($"No node-local chat client was resolved for model '{agentNode.ModelId}' (node '{agentNode.Id}').");
                        var agent = BuildAgent(agentNode, agentClient);

                        // The executor id MAF registers for an AIAgent binding is "{name}_{agentId}" — NOT bare agent.Id —
                        // so resolve it from the materialized ExecutorBinding (its .Id), which is what events surface and
                        // what a targeted SendMessageAsync must address. (Note: agent.Id is NOT the executor id.)
                        // ForwardIncomingMessages=false: an agent must NOT re-forward the messages it received (that
                        // broadcasts the upstream/seed turns to every downstream agent and double-pumps the chain — without
                        // this the Start seed reaches every downstream agent). The agent still emits its own response,
                        // which the transform/End consumes. EmitAgentUpdateEvents=true surfaces streamed assistant text.
                        var hostOptions = new AIAgentHostOptions
                        {
                            ForwardIncomingMessages = false,
                            EmitAgentUpdateEvents = true
                        };
                        var agentBinding = agent.BindAsExecutor(hostOptions);
                        agentExecutorIdToNodeId[agentBinding.Id] = agentNode.Id;
                        plans.Add(new NodePlan(node.Kind, node.Id, agentBinding.Id, agentBinding));
                        break;
                    }

                case PreviewNodeKind.Debug:
                    {
                        var debug = PreviewExecutors.BuildDebugTap(node.Id);
                        debugExecutorIdToNodeId[node.Id] = node.Id;
                        plans.Add(new NodePlan(node.Kind, node.Id, node.Id, debug));
                        break;
                    }

                case PreviewNodeKind.Pause:
                    {
                        var port = RequestPort.Create<string, string>(node.Id);
                        requestPortIdToNodeId[node.Id] = node.Id;
                        plans.Add(new NodePlan(node.Kind, node.Id, node.Id, port));
                        break;
                    }

                case PreviewNodeKind.End:
                    {
                        var end = PreviewExecutors.BuildEnd(EndExecutorId);
                        plans.Add(new NodePlan(node.Kind, node.Id, EndExecutorId, end));
                        break;
                    }

                default:
                    throw new ArgumentOutOfRangeException(nameof(definition),
                        $"Unsupported preview node kind '{node.Kind}'.");
            }
        }

        // Pass 2 — build the Start executor now that the first downstream executor id is known, then wire the chain.
        // Every message a Start/transform sends is TARGETED at the next executor id (untargeted SendMessageAsync
        // broadcasts a TurnToken to ALL agents, which double-pumps the chain).
        var startPlan = plans[0];
        if (startPlan.Kind != PreviewNodeKind.Start)
        {
            throw new ArgumentException("A preview workflow must begin with a Start node.", nameof(definition));
        }

        var startBinding = PreviewExecutors.BuildStart(StartExecutorId, definition.StartText, plans[1].ExecutorId);
        var builder = new WorkflowBuilder(startBinding);

        ExecutorBinding previousBinding = startBinding;
        for (var i = 1; i < plans.Count; i++)
        {
            var current = plans[i];
            var currentBinding = current.Binding
                                 ?? throw new InvalidOperationException($"Node '{current.NodeId}' has no executor binding.");

            if (current.Kind == PreviewNodeKind.Pause)
            {
                // Pause = RequestPort<string,string>. Adapt the upstream List<ChatMessage> to the string the port
                // expects (pre), then adapt the resumed string back to a re-seeded message + TurnToken for the
                // downstream node (post). The post-adapter targets the NEXT executor (must exist — Pause is never last,
                // End follows it).
                var nextPlan = plans[i + 1];
                var preAdapter = PreviewExecutors.BuildPausePreAdapter($"preview-pause-pre-{i}");
                var postAdapter = PreviewExecutors.BuildPausePostAdapter($"preview-pause-post-{i}", nextPlan.ExecutorId);

                _ = builder.AddEdge(previousBinding, preAdapter);
                _ = builder.AddEdge(preAdapter, currentBinding);
                _ = builder.AddEdge(currentBinding, postAdapter);
                previousBinding = postAdapter;
                continue;
            }

            var needsTransform = plans[i - 1].Kind == PreviewNodeKind.Agent && current.Kind == PreviewNodeKind.Agent;
            if (needsTransform)
            {
                var transform = PreviewExecutors.BuildTransform($"preview-transform-{i}", current.ExecutorId);
                _ = builder.AddEdge(previousBinding, transform);
                _ = builder.AddEdge(transform, currentBinding);
            }
            else
            {
                _ = builder.AddEdge(previousBinding, currentBinding);
            }

            previousBinding = currentBinding;
        }

        var endBinding = plans[^1].Binding
                         ?? throw new InvalidOperationException("The End node has no executor binding.");
        _ = builder.WithOutputFrom(endBinding);
        var workflow = builder.Build();

        var runId = $"preview-{Guid.NewGuid():N}";
        var streamingRun = await InProcessExecution
                                 .RunStreamingAsync(workflow, definition.StartText, runId, cancellationToken)
                                 .ConfigureAwait(false);

        return new PreviewWorkflowRunSession(streamingRun,
            agentExecutorIdToNodeId,
            debugExecutorIdToNodeId,
            requestPortIdToNodeId,
            _logger);
    }

    private AIAgent BuildAgent(PreviewAgentNode node, IChatClient chatClient)
    {
        // Mirror MafPlaybookEvalAgentRunner / DefaultPlaybookAnalysisAgent: a ChatClientAgent over the caller-supplied
        // node-local client with an empty tool set (basic variant — no tools). Instructions ride ChatOptions.Instructions
        // (passed via the ctor), NOT a system message in the routed list — so the transform's isolation holds.
        return new ChatClientAgent(chatClient,
            name: node.Id,
            instructions: node.Instructions,
            description: node.Label,
            tools: new List<AITool>(),
            loggerFactory: _loggerFactory,
            services: _serviceProvider);
    }

    /// <summary>
    ///     Walks the linear graph from the Start node along its single out-edge to produce an ordered node list. The
    ///     definition validator guarantees exactly one Start, one reachable End, and in/out-degree ≤ 1, so a single
    ///     forward walk is total and deterministic.
    /// </summary>
    private static IReadOnlyList<PreviewWorkflowNode> OrderLinearChain(PreviewWorkflowDefinition definition)
    {
        var nodesById = definition.Nodes.ToDictionary(node => node.Id, StringComparer.Ordinal);
        var nextBySource = definition.Edges.ToDictionary(edge => edge.SourceId, edge => edge.TargetId, StringComparer.Ordinal);

        var start = definition.Nodes.SingleOrDefault(node => node.Kind == PreviewNodeKind.Start)
                    ?? throw new ArgumentException("A preview workflow must declare exactly one Start node.", nameof(definition));

        var ordered = new List<PreviewWorkflowNode>();
        var visited = new HashSet<string>(StringComparer.Ordinal);
        var current = start;
        while (true)
        {
            if (!visited.Add(current.Id))
            {
                throw new ArgumentException("Preview workflow graph is cyclic; only linear chains are supported.", nameof(definition));
            }

            ordered.Add(current);
            if (current.Kind == PreviewNodeKind.End)
            {
                break;
            }

            if (!nextBySource.TryGetValue(current.Id, out var nextId))
            {
                throw new ArgumentException($"Preview node '{current.Id}' has no outgoing edge and is not an End node.", nameof(definition));
            }

            if (!nodesById.TryGetValue(nextId, out var next))
            {
                throw new ArgumentException($"Preview edge targets unknown node '{nextId}'.", nameof(definition));
            }

            current = next;
        }

        return ordered;
    }

    /// <summary>Per-node build record: the MAF executor id surfaced in events + its binding (null only for Start, built in pass 2).</summary>
    private sealed record NodePlan(PreviewNodeKind Kind, string NodeId, string ExecutorId, ExecutorBinding? Binding);
}
