/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutAgentsRouteImport } from './routes/_layout/agents'
import { Route as LayoutBenchmarksRouteImport } from './routes/_layout/benchmarks'
import { Route as LayoutChatRouteImport } from './routes/_layout/chat'
import { Route as LayoutCloudSettingsRouteImport } from './routes/_layout/cloud-settings'
import { Route as LayoutCommandsRouteImport } from './routes/_layout/commands'
import { Route as LayoutCustomToolsRouteImport } from './routes/_layout/custom-tools'
import { Route as LayoutDashboardRouteImport } from './routes/_layout/dashboard'
import { Route as LayoutDevelopmentRouteImport } from './routes/_layout/development'
import { Route as LayoutDiagnosticsRouteImport } from './routes/_layout/diagnostics'
import { Route as LayoutImagesRouteImport } from './routes/_layout/images'
import { Route as LayoutInvocationsRouteImport } from './routes/_layout/invocations'
import { Route as LayoutKnowledgeBaseRouteImport } from './routes/_layout/knowledge-base'
import { Route as LayoutLoadedModelsRouteImport } from './routes/_layout/loaded-models'
import { Route as LayoutMcpRouteImport } from './routes/_layout/mcp'
import { Route as LayoutModelRecommendationsRouteImport } from './routes/_layout/model-recommendations'
import { Route as LayoutModelsRouteImport } from './routes/_layout/models'
import { Route as LayoutNodeBindingRouteImport } from './routes/_layout/node-binding'
import { Route as LayoutNodeSettingsRouteImport } from './routes/_layout/node-settings'
import { Route as LayoutPreviewRouteImport } from './routes/_layout/preview'
import { Route as LayoutSchedulerRouteImport } from './routes/_layout/scheduler'
import { Route as LayoutSkillsRouteImport } from './routes/_layout/skills'
import { Route as LayoutToolsRouteImport } from './routes/_layout/tools'
import { Route as LayoutUsageRouteImport } from './routes/_layout/usage'
import { Route as LayoutTrainingIndexRouteImport } from './routes/_layout/training.index'
import { Route as LayoutTrainingComparisonsRouteImport } from './routes/_layout/training.comparisons'
import { Route as LayoutTrainingDatasetsRouteImport } from './routes/_layout/training.datasets'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAgentsRoute = LayoutAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBenchmarksRoute = LayoutBenchmarksRouteImport.update({
  id: '/benchmarks',
  path: '/benchmarks',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutChatRoute = LayoutChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCloudSettingsRoute = LayoutCloudSettingsRouteImport.update({
  id: '/cloud-settings',
  path: '/cloud-settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCommandsRoute = LayoutCommandsRouteImport.update({
  id: '/commands',
  path: '/commands',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCustomToolsRoute = LayoutCustomToolsRouteImport.update({
  id: '/custom-tools',
  path: '/custom-tools',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDevelopmentRoute = LayoutDevelopmentRouteImport.update({
  id: '/development',
  path: '/development',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDiagnosticsRoute = LayoutDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutImagesRoute = LayoutImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutInvocationsRoute = LayoutInvocationsRouteImport.update({
  id: '/invocations',
  path: '/invocations',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutKnowledgeBaseRoute = LayoutKnowledgeBaseRouteImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLoadedModelsRoute = LayoutLoadedModelsRouteImport.update({
  id: '/loaded-models',
  path: '/loaded-models',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMcpRoute = LayoutMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutModelRecommendationsRoute =
  LayoutModelRecommendationsRouteImport.update({
    id: '/model-recommendations',
    path: '/model-recommendations',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutModelsRoute = LayoutModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNodeBindingRoute = LayoutNodeBindingRouteImport.update({
  id: '/node-binding',
  path: '/node-binding',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNodeSettingsRoute = LayoutNodeSettingsRouteImport.update({
  id: '/node-settings',
  path: '/node-settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPreviewRoute = LayoutPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSchedulerRoute = LayoutSchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSkillsRoute = LayoutSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutToolsRoute = LayoutToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUsageRoute = LayoutUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTrainingIndexRoute = LayoutTrainingIndexRouteImport.update({
  id: '/training/',
  path: '/training/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTrainingComparisonsRoute =
  LayoutTrainingComparisonsRouteImport.update({
    id: '/training/comparisons',
    path: '/training/comparisons',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutTrainingDatasetsRoute = LayoutTrainingDatasetsRouteImport.update({
  id: '/training/datasets',
  path: '/training/datasets',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/agents': typeof LayoutAgentsRoute
  '/benchmarks': typeof LayoutBenchmarksRoute
  '/chat': typeof LayoutChatRoute
  '/cloud-settings': typeof LayoutCloudSettingsRoute
  '/commands': typeof LayoutCommandsRoute
  '/custom-tools': typeof LayoutCustomToolsRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/development': typeof LayoutDevelopmentRoute
  '/diagnostics': typeof LayoutDiagnosticsRoute
  '/images': typeof LayoutImagesRoute
  '/invocations': typeof LayoutInvocationsRoute
  '/knowledge-base': typeof LayoutKnowledgeBaseRoute
  '/loaded-models': typeof LayoutLoadedModelsRoute
  '/mcp': typeof LayoutMcpRoute
  '/model-recommendations': typeof LayoutModelRecommendationsRoute
  '/models': typeof LayoutModelsRoute
  '/node-binding': typeof LayoutNodeBindingRoute
  '/node-settings': typeof LayoutNodeSettingsRoute
  '/preview': typeof LayoutPreviewRoute
  '/scheduler': typeof LayoutSchedulerRoute
  '/skills': typeof LayoutSkillsRoute
  '/tools': typeof LayoutToolsRoute
  '/usage': typeof LayoutUsageRoute
  '/training/comparisons': typeof LayoutTrainingComparisonsRoute
  '/training/datasets': typeof LayoutTrainingDatasetsRoute
  '/training/': typeof LayoutTrainingIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/agents': typeof LayoutAgentsRoute
  '/benchmarks': typeof LayoutBenchmarksRoute
  '/chat': typeof LayoutChatRoute
  '/cloud-settings': typeof LayoutCloudSettingsRoute
  '/commands': typeof LayoutCommandsRoute
  '/custom-tools': typeof LayoutCustomToolsRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/development': typeof LayoutDevelopmentRoute
  '/diagnostics': typeof LayoutDiagnosticsRoute
  '/images': typeof LayoutImagesRoute
  '/invocations': typeof LayoutInvocationsRoute
  '/knowledge-base': typeof LayoutKnowledgeBaseRoute
  '/loaded-models': typeof LayoutLoadedModelsRoute
  '/mcp': typeof LayoutMcpRoute
  '/model-recommendations': typeof LayoutModelRecommendationsRoute
  '/models': typeof LayoutModelsRoute
  '/node-binding': typeof LayoutNodeBindingRoute
  '/node-settings': typeof LayoutNodeSettingsRoute
  '/preview': typeof LayoutPreviewRoute
  '/scheduler': typeof LayoutSchedulerRoute
  '/skills': typeof LayoutSkillsRoute
  '/tools': typeof LayoutToolsRoute
  '/usage': typeof LayoutUsageRoute
  '/': typeof LayoutIndexRoute
  '/training/comparisons': typeof LayoutTrainingComparisonsRoute
  '/training/datasets': typeof LayoutTrainingDatasetsRoute
  '/training': typeof LayoutTrainingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_layout/agents': typeof LayoutAgentsRoute
  '/_layout/benchmarks': typeof LayoutBenchmarksRoute
  '/_layout/chat': typeof LayoutChatRoute
  '/_layout/cloud-settings': typeof LayoutCloudSettingsRoute
  '/_layout/commands': typeof LayoutCommandsRoute
  '/_layout/custom-tools': typeof LayoutCustomToolsRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/development': typeof LayoutDevelopmentRoute
  '/_layout/diagnostics': typeof LayoutDiagnosticsRoute
  '/_layout/images': typeof LayoutImagesRoute
  '/_layout/invocations': typeof LayoutInvocationsRoute
  '/_layout/knowledge-base': typeof LayoutKnowledgeBaseRoute
  '/_layout/loaded-models': typeof LayoutLoadedModelsRoute
  '/_layout/mcp': typeof LayoutMcpRoute
  '/_layout/model-recommendations': typeof LayoutModelRecommendationsRoute
  '/_layout/models': typeof LayoutModelsRoute
  '/_layout/node-binding': typeof LayoutNodeBindingRoute
  '/_layout/node-settings': typeof LayoutNodeSettingsRoute
  '/_layout/preview': typeof LayoutPreviewRoute
  '/_layout/scheduler': typeof LayoutSchedulerRoute
  '/_layout/skills': typeof LayoutSkillsRoute
  '/_layout/tools': typeof LayoutToolsRoute
  '/_layout/usage': typeof LayoutUsageRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/training/comparisons': typeof LayoutTrainingComparisonsRoute
  '/_layout/training/datasets': typeof LayoutTrainingDatasetsRoute
  '/_layout/training/': typeof LayoutTrainingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/agents'
    | '/benchmarks'
    | '/chat'
    | '/cloud-settings'
    | '/commands'
    | '/custom-tools'
    | '/dashboard'
    | '/development'
    | '/diagnostics'
    | '/images'
    | '/invocations'
    | '/knowledge-base'
    | '/loaded-models'
    | '/mcp'
    | '/model-recommendations'
    | '/models'
    | '/node-binding'
    | '/node-settings'
    | '/preview'
    | '/scheduler'
    | '/skills'
    | '/tools'
    | '/usage'
    | '/training/comparisons'
    | '/training/datasets'
    | '/training/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/setup'
    | '/agents'
    | '/benchmarks'
    | '/chat'
    | '/cloud-settings'
    | '/commands'
    | '/custom-tools'
    | '/dashboard'
    | '/development'
    | '/diagnostics'
    | '/images'
    | '/invocations'
    | '/knowledge-base'
    | '/loaded-models'
    | '/mcp'
    | '/model-recommendations'
    | '/models'
    | '/node-binding'
    | '/node-settings'
    | '/preview'
    | '/scheduler'
    | '/skills'
    | '/tools'
    | '/usage'
    | '/'
    | '/training/comparisons'
    | '/training/datasets'
    | '/training'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/setup'
    | '/_layout/agents'
    | '/_layout/benchmarks'
    | '/_layout/chat'
    | '/_layout/cloud-settings'
    | '/_layout/commands'
    | '/_layout/custom-tools'
    | '/_layout/dashboard'
    | '/_layout/development'
    | '/_layout/diagnostics'
    | '/_layout/images'
    | '/_layout/invocations'
    | '/_layout/knowledge-base'
    | '/_layout/loaded-models'
    | '/_layout/mcp'
    | '/_layout/model-recommendations'
    | '/_layout/models'
    | '/_layout/node-binding'
    | '/_layout/node-settings'
    | '/_layout/preview'
    | '/_layout/scheduler'
    | '/_layout/skills'
    | '/_layout/tools'
    | '/_layout/usage'
    | '/_layout/'
    | '/_layout/training/comparisons'
    | '/_layout/training/datasets'
    | '/_layout/training/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/agents': {
      id: '/_layout/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof LayoutAgentsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/benchmarks': {
      id: '/_layout/benchmarks'
      path: '/benchmarks'
      fullPath: '/benchmarks'
      preLoaderRoute: typeof LayoutBenchmarksRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/chat': {
      id: '/_layout/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof LayoutChatRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/cloud-settings': {
      id: '/_layout/cloud-settings'
      path: '/cloud-settings'
      fullPath: '/cloud-settings'
      preLoaderRoute: typeof LayoutCloudSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/commands': {
      id: '/_layout/commands'
      path: '/commands'
      fullPath: '/commands'
      preLoaderRoute: typeof LayoutCommandsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/custom-tools': {
      id: '/_layout/custom-tools'
      path: '/custom-tools'
      fullPath: '/custom-tools'
      preLoaderRoute: typeof LayoutCustomToolsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/development': {
      id: '/_layout/development'
      path: '/development'
      fullPath: '/development'
      preLoaderRoute: typeof LayoutDevelopmentRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/diagnostics': {
      id: '/_layout/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof LayoutDiagnosticsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/images': {
      id: '/_layout/images'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof LayoutImagesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/invocations': {
      id: '/_layout/invocations'
      path: '/invocations'
      fullPath: '/invocations'
      preLoaderRoute: typeof LayoutInvocationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/knowledge-base': {
      id: '/_layout/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof LayoutKnowledgeBaseRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/loaded-models': {
      id: '/_layout/loaded-models'
      path: '/loaded-models'
      fullPath: '/loaded-models'
      preLoaderRoute: typeof LayoutLoadedModelsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/mcp': {
      id: '/_layout/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof LayoutMcpRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/model-recommendations': {
      id: '/_layout/model-recommendations'
      path: '/model-recommendations'
      fullPath: '/model-recommendations'
      preLoaderRoute: typeof LayoutModelRecommendationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/models': {
      id: '/_layout/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof LayoutModelsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/node-binding': {
      id: '/_layout/node-binding'
      path: '/node-binding'
      fullPath: '/node-binding'
      preLoaderRoute: typeof LayoutNodeBindingRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/node-settings': {
      id: '/_layout/node-settings'
      path: '/node-settings'
      fullPath: '/node-settings'
      preLoaderRoute: typeof LayoutNodeSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/preview': {
      id: '/_layout/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof LayoutPreviewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/scheduler': {
      id: '/_layout/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof LayoutSchedulerRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/skills': {
      id: '/_layout/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof LayoutSkillsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tools': {
      id: '/_layout/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof LayoutToolsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/usage': {
      id: '/_layout/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof LayoutUsageRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/training/': {
      id: '/_layout/training/'
      path: '/training'
      fullPath: '/training/'
      preLoaderRoute: typeof LayoutTrainingIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/training/comparisons': {
      id: '/_layout/training/comparisons'
      path: '/training/comparisons'
      fullPath: '/training/comparisons'
      preLoaderRoute: typeof LayoutTrainingComparisonsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/training/datasets': {
      id: '/_layout/training/datasets'
      path: '/training/datasets'
      fullPath: '/training/datasets'
      preLoaderRoute: typeof LayoutTrainingDatasetsRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAgentsRoute: typeof LayoutAgentsRoute
  LayoutBenchmarksRoute: typeof LayoutBenchmarksRoute
  LayoutChatRoute: typeof LayoutChatRoute
  LayoutCloudSettingsRoute: typeof LayoutCloudSettingsRoute
  LayoutCommandsRoute: typeof LayoutCommandsRoute
  LayoutCustomToolsRoute: typeof LayoutCustomToolsRoute
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutDevelopmentRoute: typeof LayoutDevelopmentRoute
  LayoutDiagnosticsRoute: typeof LayoutDiagnosticsRoute
  LayoutImagesRoute: typeof LayoutImagesRoute
  LayoutInvocationsRoute: typeof LayoutInvocationsRoute
  LayoutKnowledgeBaseRoute: typeof LayoutKnowledgeBaseRoute
  LayoutLoadedModelsRoute: typeof LayoutLoadedModelsRoute
  LayoutMcpRoute: typeof LayoutMcpRoute
  LayoutModelRecommendationsRoute: typeof LayoutModelRecommendationsRoute
  LayoutModelsRoute: typeof LayoutModelsRoute
  LayoutNodeBindingRoute: typeof LayoutNodeBindingRoute
  LayoutNodeSettingsRoute: typeof LayoutNodeSettingsRoute
  LayoutPreviewRoute: typeof LayoutPreviewRoute
  LayoutSchedulerRoute: typeof LayoutSchedulerRoute
  LayoutSkillsRoute: typeof LayoutSkillsRoute
  LayoutToolsRoute: typeof LayoutToolsRoute
  LayoutUsageRoute: typeof LayoutUsageRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutTrainingComparisonsRoute: typeof LayoutTrainingComparisonsRoute
  LayoutTrainingDatasetsRoute: typeof LayoutTrainingDatasetsRoute
  LayoutTrainingIndexRoute: typeof LayoutTrainingIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAgentsRoute: LayoutAgentsRoute,
  LayoutBenchmarksRoute: LayoutBenchmarksRoute,
  LayoutChatRoute: LayoutChatRoute,
  LayoutCloudSettingsRoute: LayoutCloudSettingsRoute,
  LayoutCommandsRoute: LayoutCommandsRoute,
  LayoutCustomToolsRoute: LayoutCustomToolsRoute,
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutDevelopmentRoute: LayoutDevelopmentRoute,
  LayoutDiagnosticsRoute: LayoutDiagnosticsRoute,
  LayoutImagesRoute: LayoutImagesRoute,
  LayoutInvocationsRoute: LayoutInvocationsRoute,
  LayoutKnowledgeBaseRoute: LayoutKnowledgeBaseRoute,
  LayoutLoadedModelsRoute: LayoutLoadedModelsRoute,
  LayoutMcpRoute: LayoutMcpRoute,
  LayoutModelRecommendationsRoute: LayoutModelRecommendationsRoute,
  LayoutModelsRoute: LayoutModelsRoute,
  LayoutNodeBindingRoute: LayoutNodeBindingRoute,
  LayoutNodeSettingsRoute: LayoutNodeSettingsRoute,
  LayoutPreviewRoute: LayoutPreviewRoute,
  LayoutSchedulerRoute: LayoutSchedulerRoute,
  LayoutSkillsRoute: LayoutSkillsRoute,
  LayoutToolsRoute: LayoutToolsRoute,
  LayoutUsageRoute: LayoutUsageRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutTrainingComparisonsRoute: LayoutTrainingComparisonsRoute,
  LayoutTrainingDatasetsRoute: LayoutTrainingDatasetsRoute,
  LayoutTrainingIndexRoute: LayoutTrainingIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
