/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutNodeSettingsRouteImport } from './routes/_layout/node-settings'
import { Route as LayoutNodeBindingRouteImport } from './routes/_layout/node-binding'
import { Route as LayoutModelsRouteImport } from './routes/_layout/models'
import { Route as LayoutManagerRouteImport } from './routes/_layout/manager'
import { Route as LayoutInvocationsRouteImport } from './routes/_layout/invocations'
import { Route as LayoutDashboardRouteImport } from './routes/_layout/dashboard'
import { Route as LayoutCloudSettingsRouteImport } from './routes/_layout/cloud-settings'
import { Route as LayoutChatRouteImport } from './routes/_layout/chat'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNodeSettingsRoute = LayoutNodeSettingsRouteImport.update({
  id: '/node-settings',
  path: '/node-settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNodeBindingRoute = LayoutNodeBindingRouteImport.update({
  id: '/node-binding',
  path: '/node-binding',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutModelsRoute = LayoutModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutManagerRoute = LayoutManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutInvocationsRoute = LayoutInvocationsRouteImport.update({
  id: '/invocations',
  path: '/invocations',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCloudSettingsRoute = LayoutCloudSettingsRouteImport.update({
  id: '/cloud-settings',
  path: '/cloud-settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutChatRoute = LayoutChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/chat': typeof LayoutChatRoute
  '/cloud-settings': typeof LayoutCloudSettingsRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/invocations': typeof LayoutInvocationsRoute
  '/manager': typeof LayoutManagerRoute
  '/models': typeof LayoutModelsRoute
  '/node-binding': typeof LayoutNodeBindingRoute
  '/node-settings': typeof LayoutNodeSettingsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/chat': typeof LayoutChatRoute
  '/cloud-settings': typeof LayoutCloudSettingsRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/invocations': typeof LayoutInvocationsRoute
  '/manager': typeof LayoutManagerRoute
  '/models': typeof LayoutModelsRoute
  '/node-binding': typeof LayoutNodeBindingRoute
  '/node-settings': typeof LayoutNodeSettingsRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_layout/chat': typeof LayoutChatRoute
  '/_layout/cloud-settings': typeof LayoutCloudSettingsRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/invocations': typeof LayoutInvocationsRoute
  '/_layout/manager': typeof LayoutManagerRoute
  '/_layout/models': typeof LayoutModelsRoute
  '/_layout/node-binding': typeof LayoutNodeBindingRoute
  '/_layout/node-settings': typeof LayoutNodeSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/chat'
    | '/cloud-settings'
    | '/dashboard'
    | '/invocations'
    | '/manager'
    | '/models'
    | '/node-binding'
    | '/node-settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/setup'
    | '/chat'
    | '/cloud-settings'
    | '/dashboard'
    | '/invocations'
    | '/manager'
    | '/models'
    | '/node-binding'
    | '/node-settings'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/setup'
    | '/_layout/chat'
    | '/_layout/cloud-settings'
    | '/_layout/dashboard'
    | '/_layout/invocations'
    | '/_layout/manager'
    | '/_layout/models'
    | '/_layout/node-binding'
    | '/_layout/node-settings'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/node-settings': {
      id: '/_layout/node-settings'
      path: '/node-settings'
      fullPath: '/node-settings'
      preLoaderRoute: typeof LayoutNodeSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/node-binding': {
      id: '/_layout/node-binding'
      path: '/node-binding'
      fullPath: '/node-binding'
      preLoaderRoute: typeof LayoutNodeBindingRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/models': {
      id: '/_layout/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof LayoutModelsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/manager': {
      id: '/_layout/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof LayoutManagerRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/invocations': {
      id: '/_layout/invocations'
      path: '/invocations'
      fullPath: '/invocations'
      preLoaderRoute: typeof LayoutInvocationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/cloud-settings': {
      id: '/_layout/cloud-settings'
      path: '/cloud-settings'
      fullPath: '/cloud-settings'
      preLoaderRoute: typeof LayoutCloudSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/chat': {
      id: '/_layout/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof LayoutChatRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutChatRoute: typeof LayoutChatRoute
  LayoutCloudSettingsRoute: typeof LayoutCloudSettingsRoute
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutInvocationsRoute: typeof LayoutInvocationsRoute
  LayoutManagerRoute: typeof LayoutManagerRoute
  LayoutModelsRoute: typeof LayoutModelsRoute
  LayoutNodeBindingRoute: typeof LayoutNodeBindingRoute
  LayoutNodeSettingsRoute: typeof LayoutNodeSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutChatRoute: LayoutChatRoute,
  LayoutCloudSettingsRoute: LayoutCloudSettingsRoute,
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutInvocationsRoute: LayoutInvocationsRoute,
  LayoutManagerRoute: LayoutManagerRoute,
  LayoutModelsRoute: LayoutModelsRoute,
  LayoutNodeBindingRoute: LayoutNodeBindingRoute,
  LayoutNodeSettingsRoute: LayoutNodeSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
