/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as ExternalAccessRouteImport } from './routes/external-access'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as UiModeSetupRouteImport } from './routes/ui-mode-setup'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutAgentRunsRouteImport } from './routes/_layout/agent-runs'
import { Route as LayoutAgentsRouteImport } from './routes/_layout/agents'
import { Route as LayoutBenchmarksRouteImport } from './routes/_layout/benchmarks'
import { Route as LayoutChatRouteImport } from './routes/_layout/chat'
import { Route as LayoutCloudSettingsRouteImport } from './routes/_layout/cloud-settings'
import { Route as LayoutCommandsRouteImport } from './routes/_layout/commands'
import { Route as LayoutCustomToolsRouteImport } from './routes/_layout/custom-tools'
import { Route as LayoutDevelopmentRouteImport } from './routes/_layout/development'
import { Route as LayoutDiagnosticsRouteImport } from './routes/_layout/diagnostics'
import { Route as LayoutExternalProvidersRouteImport } from './routes/_layout/external-providers'
import { Route as LayoutGraphWorkflowsRouteImport } from './routes/_layout/graph-workflows'
import { Route as LayoutImagesRouteImport } from './routes/_layout/images'
import { Route as LayoutInvocationsRouteImport } from './routes/_layout/invocations'
import { Route as LayoutKnowledgeBaseRouteImport } from './routes/_layout/knowledge-base'
import { Route as LayoutLoadedModelsRouteImport } from './routes/_layout/loaded-models'
import { Route as LayoutMcpRouteImport } from './routes/_layout/mcp'
import { Route as LayoutModelRecommendationsRouteImport } from './routes/_layout/model-recommendations'
import { Route as LayoutModelsRouteImport } from './routes/_layout/models'
import { Route as LayoutNodeSettingsRouteImport } from './routes/_layout/node-settings'
import { Route as LayoutSchedulerRouteImport } from './routes/_layout/scheduler'
import { Route as LayoutSkillsRouteImport } from './routes/_layout/skills'
import { Route as LayoutToolsRouteImport } from './routes/_layout/tools'
import { Route as LayoutUsageRouteImport } from './routes/_layout/usage'
import { Route as LayoutDevelopmentWorkflowsIndexRouteImport } from './routes/_layout/development-workflows.index'
import { Route as LayoutDevelopmentWorkflowsWorkItemIdRouteImport } from './routes/_layout/development-workflows.$workItemId'
import { Route as LayoutExternalAppsIndexRouteImport } from './routes/_layout/external-apps.index'
import { Route as LayoutExternalAppsCatalogRouteImport } from './routes/_layout/external-apps.catalog'
import { Route as LayoutExternalAppsInstalledRouteImport } from './routes/_layout/external-apps.installed'
import { Route as LayoutIntegrationsIndexRouteImport } from './routes/_layout/integrations.index'
import { Route as LayoutIntegrationsExecutionsRouteImport } from './routes/_layout/integrations.executions'
import { Route as LayoutIntegrationsKeysRouteImport } from './routes/_layout/integrations.keys'
import { Route as LayoutIntegrationsSessionsRouteImport } from './routes/_layout/integrations.sessions'
import { Route as LayoutIntegrationsTriggersRouteImport } from './routes/_layout/integrations.triggers'
import { Route as LayoutTrainingIndexRouteImport } from './routes/_layout/training.index'
import { Route as LayoutTrainingComparisonsRouteImport } from './routes/_layout/training.comparisons'
import { Route as LayoutTrainingDatasetsRouteImport } from './routes/_layout/training.datasets'
import { Route as LayoutTranscriptionIndexRouteImport } from './routes/_layout/transcription.index'
import { Route as LayoutTranscriptionSessionIdRouteImport } from './routes/_layout/transcription.$sessionId'
import { Route as LayoutWorkSessionsIndexRouteImport } from './routes/_layout/work-sessions.index'
import { Route as LayoutWorkSessionsSessionIdRouteImport } from './routes/_layout/work-sessions.$sessionId'
import { Route as LayoutExternalAppsInstancesInstanceIdRouteImport } from './routes/_layout/external-apps.instances.$instanceId'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const ExternalAccessRoute = ExternalAccessRouteImport.update({
  id: '/external-access',
  path: '/external-access',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const UiModeSetupRoute = UiModeSetupRouteImport.update({
  id: '/ui-mode-setup',
  path: '/ui-mode-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAgentRunsRoute = LayoutAgentRunsRouteImport.update({
  id: '/agent-runs',
  path: '/agent-runs',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAgentsRoute = LayoutAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBenchmarksRoute = LayoutBenchmarksRouteImport.update({
  id: '/benchmarks',
  path: '/benchmarks',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutChatRoute = LayoutChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCloudSettingsRoute = LayoutCloudSettingsRouteImport.update({
  id: '/cloud-settings',
  path: '/cloud-settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCommandsRoute = LayoutCommandsRouteImport.update({
  id: '/commands',
  path: '/commands',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCustomToolsRoute = LayoutCustomToolsRouteImport.update({
  id: '/custom-tools',
  path: '/custom-tools',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDevelopmentRoute = LayoutDevelopmentRouteImport.update({
  id: '/development',
  path: '/development',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDiagnosticsRoute = LayoutDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExternalProvidersRoute = LayoutExternalProvidersRouteImport.update({
  id: '/external-providers',
  path: '/external-providers',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGraphWorkflowsRoute = LayoutGraphWorkflowsRouteImport.update({
  id: '/graph-workflows',
  path: '/graph-workflows',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutImagesRoute = LayoutImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutInvocationsRoute = LayoutInvocationsRouteImport.update({
  id: '/invocations',
  path: '/invocations',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutKnowledgeBaseRoute = LayoutKnowledgeBaseRouteImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLoadedModelsRoute = LayoutLoadedModelsRouteImport.update({
  id: '/loaded-models',
  path: '/loaded-models',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMcpRoute = LayoutMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutModelRecommendationsRoute =
  LayoutModelRecommendationsRouteImport.update({
    id: '/model-recommendations',
    path: '/model-recommendations',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutModelsRoute = LayoutModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNodeSettingsRoute = LayoutNodeSettingsRouteImport.update({
  id: '/node-settings',
  path: '/node-settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSchedulerRoute = LayoutSchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSkillsRoute = LayoutSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutToolsRoute = LayoutToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUsageRoute = LayoutUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDevelopmentWorkflowsIndexRoute =
  LayoutDevelopmentWorkflowsIndexRouteImport.update({
    id: '/development-workflows/',
    path: '/development-workflows/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutDevelopmentWorkflowsWorkItemIdRoute =
  LayoutDevelopmentWorkflowsWorkItemIdRouteImport.update({
    id: '/development-workflows/$workItemId',
    path: '/development-workflows/$workItemId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutExternalAppsIndexRoute = LayoutExternalAppsIndexRouteImport.update({
  id: '/external-apps/',
  path: '/external-apps/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExternalAppsCatalogRoute =
  LayoutExternalAppsCatalogRouteImport.update({
    id: '/external-apps/catalog',
    path: '/external-apps/catalog',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutExternalAppsInstalledRoute =
  LayoutExternalAppsInstalledRouteImport.update({
    id: '/external-apps/installed',
    path: '/external-apps/installed',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutIntegrationsIndexRoute = LayoutIntegrationsIndexRouteImport.update({
  id: '/integrations/',
  path: '/integrations/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutIntegrationsExecutionsRoute =
  LayoutIntegrationsExecutionsRouteImport.update({
    id: '/integrations/executions',
    path: '/integrations/executions',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutIntegrationsKeysRoute = LayoutIntegrationsKeysRouteImport.update({
  id: '/integrations/keys',
  path: '/integrations/keys',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutIntegrationsSessionsRoute =
  LayoutIntegrationsSessionsRouteImport.update({
    id: '/integrations/sessions',
    path: '/integrations/sessions',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutIntegrationsTriggersRoute =
  LayoutIntegrationsTriggersRouteImport.update({
    id: '/integrations/triggers',
    path: '/integrations/triggers',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutTrainingIndexRoute = LayoutTrainingIndexRouteImport.update({
  id: '/training/',
  path: '/training/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTrainingComparisonsRoute =
  LayoutTrainingComparisonsRouteImport.update({
    id: '/training/comparisons',
    path: '/training/comparisons',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutTrainingDatasetsRoute = LayoutTrainingDatasetsRouteImport.update({
  id: '/training/datasets',
  path: '/training/datasets',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTranscriptionIndexRoute =
  LayoutTranscriptionIndexRouteImport.update({
    id: '/transcription/',
    path: '/transcription/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutTranscriptionSessionIdRoute =
  LayoutTranscriptionSessionIdRouteImport.update({
    id: '/transcription/$sessionId',
    path: '/transcription/$sessionId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutWorkSessionsIndexRoute = LayoutWorkSessionsIndexRouteImport.update({
  id: '/work-sessions/',
  path: '/work-sessions/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWorkSessionsSessionIdRoute =
  LayoutWorkSessionsSessionIdRouteImport.update({
    id: '/work-sessions/$sessionId',
    path: '/work-sessions/$sessionId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutExternalAppsInstancesInstanceIdRoute =
  LayoutExternalAppsInstancesInstanceIdRouteImport.update({
    id: '/external-apps/instances/$instanceId',
    path: '/external-apps/instances/$instanceId',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/external-access': typeof ExternalAccessRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/ui-mode-setup': typeof UiModeSetupRoute
  '/agent-runs': typeof LayoutAgentRunsRoute
  '/agents': typeof LayoutAgentsRoute
  '/benchmarks': typeof LayoutBenchmarksRoute
  '/chat': typeof LayoutChatRoute
  '/cloud-settings': typeof LayoutCloudSettingsRoute
  '/commands': typeof LayoutCommandsRoute
  '/custom-tools': typeof LayoutCustomToolsRoute
  '/development': typeof LayoutDevelopmentRoute
  '/diagnostics': typeof LayoutDiagnosticsRoute
  '/external-providers': typeof LayoutExternalProvidersRoute
  '/graph-workflows': typeof LayoutGraphWorkflowsRoute
  '/images': typeof LayoutImagesRoute
  '/invocations': typeof LayoutInvocationsRoute
  '/knowledge-base': typeof LayoutKnowledgeBaseRoute
  '/loaded-models': typeof LayoutLoadedModelsRoute
  '/mcp': typeof LayoutMcpRoute
  '/model-recommendations': typeof LayoutModelRecommendationsRoute
  '/models': typeof LayoutModelsRoute
  '/node-settings': typeof LayoutNodeSettingsRoute
  '/scheduler': typeof LayoutSchedulerRoute
  '/skills': typeof LayoutSkillsRoute
  '/tools': typeof LayoutToolsRoute
  '/usage': typeof LayoutUsageRoute
  '/development-workflows/$workItemId': typeof LayoutDevelopmentWorkflowsWorkItemIdRoute
  '/external-apps/catalog': typeof LayoutExternalAppsCatalogRoute
  '/external-apps/installed': typeof LayoutExternalAppsInstalledRoute
  '/integrations/executions': typeof LayoutIntegrationsExecutionsRoute
  '/integrations/keys': typeof LayoutIntegrationsKeysRoute
  '/integrations/sessions': typeof LayoutIntegrationsSessionsRoute
  '/integrations/triggers': typeof LayoutIntegrationsTriggersRoute
  '/training/comparisons': typeof LayoutTrainingComparisonsRoute
  '/training/datasets': typeof LayoutTrainingDatasetsRoute
  '/transcription/$sessionId': typeof LayoutTranscriptionSessionIdRoute
  '/work-sessions/$sessionId': typeof LayoutWorkSessionsSessionIdRoute
  '/development-workflows/': typeof LayoutDevelopmentWorkflowsIndexRoute
  '/external-apps/': typeof LayoutExternalAppsIndexRoute
  '/integrations/': typeof LayoutIntegrationsIndexRoute
  '/training/': typeof LayoutTrainingIndexRoute
  '/transcription/': typeof LayoutTranscriptionIndexRoute
  '/work-sessions/': typeof LayoutWorkSessionsIndexRoute
  '/external-apps/instances/$instanceId': typeof LayoutExternalAppsInstancesInstanceIdRoute
}
export interface FileRoutesByTo {
  '/external-access': typeof ExternalAccessRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/ui-mode-setup': typeof UiModeSetupRoute
  '/agent-runs': typeof LayoutAgentRunsRoute
  '/agents': typeof LayoutAgentsRoute
  '/benchmarks': typeof LayoutBenchmarksRoute
  '/chat': typeof LayoutChatRoute
  '/cloud-settings': typeof LayoutCloudSettingsRoute
  '/commands': typeof LayoutCommandsRoute
  '/custom-tools': typeof LayoutCustomToolsRoute
  '/development': typeof LayoutDevelopmentRoute
  '/diagnostics': typeof LayoutDiagnosticsRoute
  '/external-providers': typeof LayoutExternalProvidersRoute
  '/graph-workflows': typeof LayoutGraphWorkflowsRoute
  '/images': typeof LayoutImagesRoute
  '/invocations': typeof LayoutInvocationsRoute
  '/knowledge-base': typeof LayoutKnowledgeBaseRoute
  '/loaded-models': typeof LayoutLoadedModelsRoute
  '/mcp': typeof LayoutMcpRoute
  '/model-recommendations': typeof LayoutModelRecommendationsRoute
  '/models': typeof LayoutModelsRoute
  '/node-settings': typeof LayoutNodeSettingsRoute
  '/scheduler': typeof LayoutSchedulerRoute
  '/skills': typeof LayoutSkillsRoute
  '/tools': typeof LayoutToolsRoute
  '/usage': typeof LayoutUsageRoute
  '/': typeof LayoutIndexRoute
  '/development-workflows/$workItemId': typeof LayoutDevelopmentWorkflowsWorkItemIdRoute
  '/external-apps/catalog': typeof LayoutExternalAppsCatalogRoute
  '/external-apps/installed': typeof LayoutExternalAppsInstalledRoute
  '/integrations/executions': typeof LayoutIntegrationsExecutionsRoute
  '/integrations/keys': typeof LayoutIntegrationsKeysRoute
  '/integrations/sessions': typeof LayoutIntegrationsSessionsRoute
  '/integrations/triggers': typeof LayoutIntegrationsTriggersRoute
  '/training/comparisons': typeof LayoutTrainingComparisonsRoute
  '/training/datasets': typeof LayoutTrainingDatasetsRoute
  '/transcription/$sessionId': typeof LayoutTranscriptionSessionIdRoute
  '/work-sessions/$sessionId': typeof LayoutWorkSessionsSessionIdRoute
  '/development-workflows': typeof LayoutDevelopmentWorkflowsIndexRoute
  '/external-apps': typeof LayoutExternalAppsIndexRoute
  '/integrations': typeof LayoutIntegrationsIndexRoute
  '/training': typeof LayoutTrainingIndexRoute
  '/transcription': typeof LayoutTranscriptionIndexRoute
  '/work-sessions': typeof LayoutWorkSessionsIndexRoute
  '/external-apps/instances/$instanceId': typeof LayoutExternalAppsInstancesInstanceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/external-access': typeof ExternalAccessRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/ui-mode-setup': typeof UiModeSetupRoute
  '/_layout/agent-runs': typeof LayoutAgentRunsRoute
  '/_layout/agents': typeof LayoutAgentsRoute
  '/_layout/benchmarks': typeof LayoutBenchmarksRoute
  '/_layout/chat': typeof LayoutChatRoute
  '/_layout/cloud-settings': typeof LayoutCloudSettingsRoute
  '/_layout/commands': typeof LayoutCommandsRoute
  '/_layout/custom-tools': typeof LayoutCustomToolsRoute
  '/_layout/development': typeof LayoutDevelopmentRoute
  '/_layout/diagnostics': typeof LayoutDiagnosticsRoute
  '/_layout/external-providers': typeof LayoutExternalProvidersRoute
  '/_layout/graph-workflows': typeof LayoutGraphWorkflowsRoute
  '/_layout/images': typeof LayoutImagesRoute
  '/_layout/invocations': typeof LayoutInvocationsRoute
  '/_layout/knowledge-base': typeof LayoutKnowledgeBaseRoute
  '/_layout/loaded-models': typeof LayoutLoadedModelsRoute
  '/_layout/mcp': typeof LayoutMcpRoute
  '/_layout/model-recommendations': typeof LayoutModelRecommendationsRoute
  '/_layout/models': typeof LayoutModelsRoute
  '/_layout/node-settings': typeof LayoutNodeSettingsRoute
  '/_layout/scheduler': typeof LayoutSchedulerRoute
  '/_layout/skills': typeof LayoutSkillsRoute
  '/_layout/tools': typeof LayoutToolsRoute
  '/_layout/usage': typeof LayoutUsageRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/development-workflows/$workItemId': typeof LayoutDevelopmentWorkflowsWorkItemIdRoute
  '/_layout/external-apps/catalog': typeof LayoutExternalAppsCatalogRoute
  '/_layout/external-apps/installed': typeof LayoutExternalAppsInstalledRoute
  '/_layout/integrations/executions': typeof LayoutIntegrationsExecutionsRoute
  '/_layout/integrations/keys': typeof LayoutIntegrationsKeysRoute
  '/_layout/integrations/sessions': typeof LayoutIntegrationsSessionsRoute
  '/_layout/integrations/triggers': typeof LayoutIntegrationsTriggersRoute
  '/_layout/training/comparisons': typeof LayoutTrainingComparisonsRoute
  '/_layout/training/datasets': typeof LayoutTrainingDatasetsRoute
  '/_layout/transcription/$sessionId': typeof LayoutTranscriptionSessionIdRoute
  '/_layout/work-sessions/$sessionId': typeof LayoutWorkSessionsSessionIdRoute
  '/_layout/development-workflows/': typeof LayoutDevelopmentWorkflowsIndexRoute
  '/_layout/external-apps/': typeof LayoutExternalAppsIndexRoute
  '/_layout/integrations/': typeof LayoutIntegrationsIndexRoute
  '/_layout/training/': typeof LayoutTrainingIndexRoute
  '/_layout/transcription/': typeof LayoutTranscriptionIndexRoute
  '/_layout/work-sessions/': typeof LayoutWorkSessionsIndexRoute
  '/_layout/external-apps/instances/$instanceId': typeof LayoutExternalAppsInstancesInstanceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/external-access'
    | '/login'
    | '/setup'
    | '/ui-mode-setup'
    | '/agent-runs'
    | '/agents'
    | '/benchmarks'
    | '/chat'
    | '/cloud-settings'
    | '/commands'
    | '/custom-tools'
    | '/development'
    | '/diagnostics'
    | '/external-providers'
    | '/graph-workflows'
    | '/images'
    | '/invocations'
    | '/knowledge-base'
    | '/loaded-models'
    | '/mcp'
    | '/model-recommendations'
    | '/models'
    | '/node-settings'
    | '/scheduler'
    | '/skills'
    | '/tools'
    | '/usage'
    | '/development-workflows/$workItemId'
    | '/external-apps/catalog'
    | '/external-apps/installed'
    | '/integrations/executions'
    | '/integrations/keys'
    | '/integrations/sessions'
    | '/integrations/triggers'
    | '/training/comparisons'
    | '/training/datasets'
    | '/transcription/$sessionId'
    | '/work-sessions/$sessionId'
    | '/development-workflows/'
    | '/external-apps/'
    | '/integrations/'
    | '/training/'
    | '/transcription/'
    | '/work-sessions/'
    | '/external-apps/instances/$instanceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/external-access'
    | '/login'
    | '/setup'
    | '/ui-mode-setup'
    | '/agent-runs'
    | '/agents'
    | '/benchmarks'
    | '/chat'
    | '/cloud-settings'
    | '/commands'
    | '/custom-tools'
    | '/development'
    | '/diagnostics'
    | '/external-providers'
    | '/graph-workflows'
    | '/images'
    | '/invocations'
    | '/knowledge-base'
    | '/loaded-models'
    | '/mcp'
    | '/model-recommendations'
    | '/models'
    | '/node-settings'
    | '/scheduler'
    | '/skills'
    | '/tools'
    | '/usage'
    | '/'
    | '/development-workflows/$workItemId'
    | '/external-apps/catalog'
    | '/external-apps/installed'
    | '/integrations/executions'
    | '/integrations/keys'
    | '/integrations/sessions'
    | '/integrations/triggers'
    | '/training/comparisons'
    | '/training/datasets'
    | '/transcription/$sessionId'
    | '/work-sessions/$sessionId'
    | '/development-workflows'
    | '/external-apps'
    | '/integrations'
    | '/training'
    | '/transcription'
    | '/work-sessions'
    | '/external-apps/instances/$instanceId'
  id:
    | '__root__'
    | '/_layout'
    | '/external-access'
    | '/login'
    | '/setup'
    | '/ui-mode-setup'
    | '/_layout/agent-runs'
    | '/_layout/agents'
    | '/_layout/benchmarks'
    | '/_layout/chat'
    | '/_layout/cloud-settings'
    | '/_layout/commands'
    | '/_layout/custom-tools'
    | '/_layout/development'
    | '/_layout/diagnostics'
    | '/_layout/external-providers'
    | '/_layout/graph-workflows'
    | '/_layout/images'
    | '/_layout/invocations'
    | '/_layout/knowledge-base'
    | '/_layout/loaded-models'
    | '/_layout/mcp'
    | '/_layout/model-recommendations'
    | '/_layout/models'
    | '/_layout/node-settings'
    | '/_layout/scheduler'
    | '/_layout/skills'
    | '/_layout/tools'
    | '/_layout/usage'
    | '/_layout/'
    | '/_layout/development-workflows/$workItemId'
    | '/_layout/external-apps/catalog'
    | '/_layout/external-apps/installed'
    | '/_layout/integrations/executions'
    | '/_layout/integrations/keys'
    | '/_layout/integrations/sessions'
    | '/_layout/integrations/triggers'
    | '/_layout/training/comparisons'
    | '/_layout/training/datasets'
    | '/_layout/transcription/$sessionId'
    | '/_layout/work-sessions/$sessionId'
    | '/_layout/development-workflows/'
    | '/_layout/external-apps/'
    | '/_layout/integrations/'
    | '/_layout/training/'
    | '/_layout/transcription/'
    | '/_layout/work-sessions/'
    | '/_layout/external-apps/instances/$instanceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  ExternalAccessRoute: typeof ExternalAccessRoute
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  UiModeSetupRoute: typeof UiModeSetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/external-access': {
      id: '/external-access'
      path: '/external-access'
      fullPath: '/external-access'
      preLoaderRoute: typeof ExternalAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui-mode-setup': {
      id: '/ui-mode-setup'
      path: '/ui-mode-setup'
      fullPath: '/ui-mode-setup'
      preLoaderRoute: typeof UiModeSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/agent-runs': {
      id: '/_layout/agent-runs'
      path: '/agent-runs'
      fullPath: '/agent-runs'
      preLoaderRoute: typeof LayoutAgentRunsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/agents': {
      id: '/_layout/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof LayoutAgentsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/benchmarks': {
      id: '/_layout/benchmarks'
      path: '/benchmarks'
      fullPath: '/benchmarks'
      preLoaderRoute: typeof LayoutBenchmarksRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/chat': {
      id: '/_layout/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof LayoutChatRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/cloud-settings': {
      id: '/_layout/cloud-settings'
      path: '/cloud-settings'
      fullPath: '/cloud-settings'
      preLoaderRoute: typeof LayoutCloudSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/commands': {
      id: '/_layout/commands'
      path: '/commands'
      fullPath: '/commands'
      preLoaderRoute: typeof LayoutCommandsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/custom-tools': {
      id: '/_layout/custom-tools'
      path: '/custom-tools'
      fullPath: '/custom-tools'
      preLoaderRoute: typeof LayoutCustomToolsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/development': {
      id: '/_layout/development'
      path: '/development'
      fullPath: '/development'
      preLoaderRoute: typeof LayoutDevelopmentRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/diagnostics': {
      id: '/_layout/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof LayoutDiagnosticsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/external-providers': {
      id: '/_layout/external-providers'
      path: '/external-providers'
      fullPath: '/external-providers'
      preLoaderRoute: typeof LayoutExternalProvidersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/graph-workflows': {
      id: '/_layout/graph-workflows'
      path: '/graph-workflows'
      fullPath: '/graph-workflows'
      preLoaderRoute: typeof LayoutGraphWorkflowsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/images': {
      id: '/_layout/images'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof LayoutImagesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/invocations': {
      id: '/_layout/invocations'
      path: '/invocations'
      fullPath: '/invocations'
      preLoaderRoute: typeof LayoutInvocationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/knowledge-base': {
      id: '/_layout/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof LayoutKnowledgeBaseRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/loaded-models': {
      id: '/_layout/loaded-models'
      path: '/loaded-models'
      fullPath: '/loaded-models'
      preLoaderRoute: typeof LayoutLoadedModelsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/mcp': {
      id: '/_layout/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof LayoutMcpRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/model-recommendations': {
      id: '/_layout/model-recommendations'
      path: '/model-recommendations'
      fullPath: '/model-recommendations'
      preLoaderRoute: typeof LayoutModelRecommendationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/models': {
      id: '/_layout/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof LayoutModelsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/node-settings': {
      id: '/_layout/node-settings'
      path: '/node-settings'
      fullPath: '/node-settings'
      preLoaderRoute: typeof LayoutNodeSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/scheduler': {
      id: '/_layout/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof LayoutSchedulerRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/skills': {
      id: '/_layout/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof LayoutSkillsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tools': {
      id: '/_layout/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof LayoutToolsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/usage': {
      id: '/_layout/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof LayoutUsageRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/development-workflows/': {
      id: '/_layout/development-workflows/'
      path: '/development-workflows'
      fullPath: '/development-workflows/'
      preLoaderRoute: typeof LayoutDevelopmentWorkflowsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/development-workflows/$workItemId': {
      id: '/_layout/development-workflows/$workItemId'
      path: '/development-workflows/$workItemId'
      fullPath: '/development-workflows/$workItemId'
      preLoaderRoute: typeof LayoutDevelopmentWorkflowsWorkItemIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/external-apps/': {
      id: '/_layout/external-apps/'
      path: '/external-apps'
      fullPath: '/external-apps/'
      preLoaderRoute: typeof LayoutExternalAppsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/external-apps/catalog': {
      id: '/_layout/external-apps/catalog'
      path: '/external-apps/catalog'
      fullPath: '/external-apps/catalog'
      preLoaderRoute: typeof LayoutExternalAppsCatalogRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/external-apps/installed': {
      id: '/_layout/external-apps/installed'
      path: '/external-apps/installed'
      fullPath: '/external-apps/installed'
      preLoaderRoute: typeof LayoutExternalAppsInstalledRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/integrations/': {
      id: '/_layout/integrations/'
      path: '/integrations'
      fullPath: '/integrations/'
      preLoaderRoute: typeof LayoutIntegrationsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/integrations/executions': {
      id: '/_layout/integrations/executions'
      path: '/integrations/executions'
      fullPath: '/integrations/executions'
      preLoaderRoute: typeof LayoutIntegrationsExecutionsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/integrations/keys': {
      id: '/_layout/integrations/keys'
      path: '/integrations/keys'
      fullPath: '/integrations/keys'
      preLoaderRoute: typeof LayoutIntegrationsKeysRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/integrations/sessions': {
      id: '/_layout/integrations/sessions'
      path: '/integrations/sessions'
      fullPath: '/integrations/sessions'
      preLoaderRoute: typeof LayoutIntegrationsSessionsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/integrations/triggers': {
      id: '/_layout/integrations/triggers'
      path: '/integrations/triggers'
      fullPath: '/integrations/triggers'
      preLoaderRoute: typeof LayoutIntegrationsTriggersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/training/': {
      id: '/_layout/training/'
      path: '/training'
      fullPath: '/training/'
      preLoaderRoute: typeof LayoutTrainingIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/training/comparisons': {
      id: '/_layout/training/comparisons'
      path: '/training/comparisons'
      fullPath: '/training/comparisons'
      preLoaderRoute: typeof LayoutTrainingComparisonsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/training/datasets': {
      id: '/_layout/training/datasets'
      path: '/training/datasets'
      fullPath: '/training/datasets'
      preLoaderRoute: typeof LayoutTrainingDatasetsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/transcription/': {
      id: '/_layout/transcription/'
      path: '/transcription'
      fullPath: '/transcription/'
      preLoaderRoute: typeof LayoutTranscriptionIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/transcription/$sessionId': {
      id: '/_layout/transcription/$sessionId'
      path: '/transcription/$sessionId'
      fullPath: '/transcription/$sessionId'
      preLoaderRoute: typeof LayoutTranscriptionSessionIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/work-sessions/': {
      id: '/_layout/work-sessions/'
      path: '/work-sessions'
      fullPath: '/work-sessions/'
      preLoaderRoute: typeof LayoutWorkSessionsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/work-sessions/$sessionId': {
      id: '/_layout/work-sessions/$sessionId'
      path: '/work-sessions/$sessionId'
      fullPath: '/work-sessions/$sessionId'
      preLoaderRoute: typeof LayoutWorkSessionsSessionIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/external-apps/instances/$instanceId': {
      id: '/_layout/external-apps/instances/$instanceId'
      path: '/external-apps/instances/$instanceId'
      fullPath: '/external-apps/instances/$instanceId'
      preLoaderRoute: typeof LayoutExternalAppsInstancesInstanceIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAgentRunsRoute: typeof LayoutAgentRunsRoute
  LayoutAgentsRoute: typeof LayoutAgentsRoute
  LayoutBenchmarksRoute: typeof LayoutBenchmarksRoute
  LayoutChatRoute: typeof LayoutChatRoute
  LayoutCloudSettingsRoute: typeof LayoutCloudSettingsRoute
  LayoutCommandsRoute: typeof LayoutCommandsRoute
  LayoutCustomToolsRoute: typeof LayoutCustomToolsRoute
  LayoutDevelopmentRoute: typeof LayoutDevelopmentRoute
  LayoutDiagnosticsRoute: typeof LayoutDiagnosticsRoute
  LayoutExternalProvidersRoute: typeof LayoutExternalProvidersRoute
  LayoutGraphWorkflowsRoute: typeof LayoutGraphWorkflowsRoute
  LayoutImagesRoute: typeof LayoutImagesRoute
  LayoutInvocationsRoute: typeof LayoutInvocationsRoute
  LayoutKnowledgeBaseRoute: typeof LayoutKnowledgeBaseRoute
  LayoutLoadedModelsRoute: typeof LayoutLoadedModelsRoute
  LayoutMcpRoute: typeof LayoutMcpRoute
  LayoutModelRecommendationsRoute: typeof LayoutModelRecommendationsRoute
  LayoutModelsRoute: typeof LayoutModelsRoute
  LayoutNodeSettingsRoute: typeof LayoutNodeSettingsRoute
  LayoutSchedulerRoute: typeof LayoutSchedulerRoute
  LayoutSkillsRoute: typeof LayoutSkillsRoute
  LayoutToolsRoute: typeof LayoutToolsRoute
  LayoutUsageRoute: typeof LayoutUsageRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutDevelopmentWorkflowsWorkItemIdRoute: typeof LayoutDevelopmentWorkflowsWorkItemIdRoute
  LayoutExternalAppsCatalogRoute: typeof LayoutExternalAppsCatalogRoute
  LayoutExternalAppsInstalledRoute: typeof LayoutExternalAppsInstalledRoute
  LayoutIntegrationsExecutionsRoute: typeof LayoutIntegrationsExecutionsRoute
  LayoutIntegrationsKeysRoute: typeof LayoutIntegrationsKeysRoute
  LayoutIntegrationsSessionsRoute: typeof LayoutIntegrationsSessionsRoute
  LayoutIntegrationsTriggersRoute: typeof LayoutIntegrationsTriggersRoute
  LayoutTrainingComparisonsRoute: typeof LayoutTrainingComparisonsRoute
  LayoutTrainingDatasetsRoute: typeof LayoutTrainingDatasetsRoute
  LayoutTranscriptionSessionIdRoute: typeof LayoutTranscriptionSessionIdRoute
  LayoutWorkSessionsSessionIdRoute: typeof LayoutWorkSessionsSessionIdRoute
  LayoutDevelopmentWorkflowsIndexRoute: typeof LayoutDevelopmentWorkflowsIndexRoute
  LayoutExternalAppsIndexRoute: typeof LayoutExternalAppsIndexRoute
  LayoutIntegrationsIndexRoute: typeof LayoutIntegrationsIndexRoute
  LayoutTrainingIndexRoute: typeof LayoutTrainingIndexRoute
  LayoutTranscriptionIndexRoute: typeof LayoutTranscriptionIndexRoute
  LayoutWorkSessionsIndexRoute: typeof LayoutWorkSessionsIndexRoute
  LayoutExternalAppsInstancesInstanceIdRoute: typeof LayoutExternalAppsInstancesInstanceIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAgentRunsRoute: LayoutAgentRunsRoute,
  LayoutAgentsRoute: LayoutAgentsRoute,
  LayoutBenchmarksRoute: LayoutBenchmarksRoute,
  LayoutChatRoute: LayoutChatRoute,
  LayoutCloudSettingsRoute: LayoutCloudSettingsRoute,
  LayoutCommandsRoute: LayoutCommandsRoute,
  LayoutCustomToolsRoute: LayoutCustomToolsRoute,
  LayoutDevelopmentRoute: LayoutDevelopmentRoute,
  LayoutDiagnosticsRoute: LayoutDiagnosticsRoute,
  LayoutExternalProvidersRoute: LayoutExternalProvidersRoute,
  LayoutGraphWorkflowsRoute: LayoutGraphWorkflowsRoute,
  LayoutImagesRoute: LayoutImagesRoute,
  LayoutInvocationsRoute: LayoutInvocationsRoute,
  LayoutKnowledgeBaseRoute: LayoutKnowledgeBaseRoute,
  LayoutLoadedModelsRoute: LayoutLoadedModelsRoute,
  LayoutMcpRoute: LayoutMcpRoute,
  LayoutModelRecommendationsRoute: LayoutModelRecommendationsRoute,
  LayoutModelsRoute: LayoutModelsRoute,
  LayoutNodeSettingsRoute: LayoutNodeSettingsRoute,
  LayoutSchedulerRoute: LayoutSchedulerRoute,
  LayoutSkillsRoute: LayoutSkillsRoute,
  LayoutToolsRoute: LayoutToolsRoute,
  LayoutUsageRoute: LayoutUsageRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutDevelopmentWorkflowsWorkItemIdRoute:
    LayoutDevelopmentWorkflowsWorkItemIdRoute,
  LayoutExternalAppsCatalogRoute: LayoutExternalAppsCatalogRoute,
  LayoutExternalAppsInstalledRoute: LayoutExternalAppsInstalledRoute,
  LayoutIntegrationsExecutionsRoute: LayoutIntegrationsExecutionsRoute,
  LayoutIntegrationsKeysRoute: LayoutIntegrationsKeysRoute,
  LayoutIntegrationsSessionsRoute: LayoutIntegrationsSessionsRoute,
  LayoutIntegrationsTriggersRoute: LayoutIntegrationsTriggersRoute,
  LayoutTrainingComparisonsRoute: LayoutTrainingComparisonsRoute,
  LayoutTrainingDatasetsRoute: LayoutTrainingDatasetsRoute,
  LayoutTranscriptionSessionIdRoute: LayoutTranscriptionSessionIdRoute,
  LayoutWorkSessionsSessionIdRoute: LayoutWorkSessionsSessionIdRoute,
  LayoutDevelopmentWorkflowsIndexRoute: LayoutDevelopmentWorkflowsIndexRoute,
  LayoutExternalAppsIndexRoute: LayoutExternalAppsIndexRoute,
  LayoutIntegrationsIndexRoute: LayoutIntegrationsIndexRoute,
  LayoutTrainingIndexRoute: LayoutTrainingIndexRoute,
  LayoutTranscriptionIndexRoute: LayoutTranscriptionIndexRoute,
  LayoutWorkSessionsIndexRoute: LayoutWorkSessionsIndexRoute,
  LayoutExternalAppsInstancesInstanceIdRoute:
    LayoutExternalAppsInstancesInstanceIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  ExternalAccessRoute: ExternalAccessRoute,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  UiModeSetupRoute: UiModeSetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
