<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>XE_Local_AI_Engine.HostAgent.Linux</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Docker.DotNet.Enhanced"/>
    <PackageReference Include="Grpc.AspNetCore"/>
    <PackageReference Include="OllamaSharp"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\XE-Local-AI-Engine.HostAgent.Abstractions\XE-Local-AI-Engine.HostAgent.Abstractions.csproj"/>
    <ProjectReference Include="..\XE-Local-AI-Engine.HostAgent.Grpc.Contracts\XE-Local-AI-Engine.HostAgent.Grpc.Contracts.csproj"/>
    <ProjectReference Include="..\XE-Local-AI-Engine.ServiceDefaults\XE-Local-AI-Engine.ServiceDefaults.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Packaging\**\*" CopyToOutputDirectory="PreserveNewest"/>
  </ItemGroup>

</Project>
