<Project>
  <Sdk Name="Aspire.AppHost.Sdk" Version="13.4.5"/>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsAspireHost>true</IsAspireHost>
    <RootNamespace>XE_Local_AI_Engine.AppHost</RootNamespace>
    <UserSecretsId>2b47b277-b0a5-4afd-90bf-b644cb1b1228</UserSecretsId>
  </PropertyGroup>

  <PropertyGroup>
    <NoWarn>$(NoWarn);ASPIREBROWSERLOGS001</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\XE-Local-AI-Engine.Client\XE-Local-AI-Engine.Client.csproj"/>
    <ProjectReference Include="..\XE-Local-AI-Engine.HostAgent.Linux\XE-Local-AI-Engine.HostAgent.Linux.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost"/>
    <PackageReference Include="Aspire.Hosting.Browsers"/>
    <PackageReference Include="Aspire.Hosting.JavaScript"/>
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.Ollama"/>
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.Sqlite"/>
  </ItemGroup>
</Project>
