namespace XE_Local_AI_Engine.Tests.Architecture.Support;

using System.Xml.Linq;
using XE_Local_AI_Engine.Tests.Testing;

/// <summary>
///     The set of C# files a source-text architecture scan is allowed to judge: every directory the solution file
///     names, plus the C# that ships outside it, minus everything generated.
/// </summary>
/// <remarks>
///     Reading the roots from the solution rather than a hand-kept list is the point: a project added tomorrow is
///     enforced the day it is added, and one whose directory cannot be found contributes no files and would be
///     exempt without anyone deciding that. <c>PrimaryConstructorConventionTests</c> asserts that every solution
///     project's directory really is found, which is the non-vacuity half no file count can give.
/// </remarks>
internal static class EnforcedSourceFiles
{
    /// <summary>C# that ships outside the solution.</summary>
    private static readonly string[] ExtraEnforcedRoots = ["tools"];

    /// <summary>Every enforced file as an absolute path and its repository-relative form, in a stable order.</summary>
    internal static IEnumerable<(string Path, string Relative)> All()
    {
        foreach (var root in EnforcedRoots())
        {
            foreach (var file in Under(root))
            {
                yield return file;
            }
        }
    }

    /// <summary>The project directory names the solution file lists, sorted.</summary>
    internal static string[] SolutionProjects() =>
        XDocument.Load(RepositoryPaths.Combine("XE-Local-AI-Engine.slnx"))
                 .Descendants("Project")
                 .Select(project => (string?)project.Attribute("Path"))
                 .Where(path => path is not null && path.EndsWith(".csproj", StringComparison.OrdinalIgnoreCase))
                 .Select(path => Path.GetFileNameWithoutExtension(path!.Replace('\\', '/')))
                 .Order(StringComparer.Ordinal)
                 .ToArray();

    private static IEnumerable<string> EnforcedRoots() =>
        SolutionProjects().Concat(ExtraEnforcedRoots).Select(root => RepositoryPaths.Combine(root));

    private static IEnumerable<(string Path, string Relative)> Under(string root)
    {
        if (!Directory.Exists(root))
        {
            yield break;
        }

        foreach (var path in Directory.EnumerateFiles(root, "*.cs", SearchOption.AllDirectories)
                                      .Order(StringComparer.Ordinal))
        {
            var relative = Path.GetRelativePath(RepositoryPaths.Root, path).Replace('\\', '/');

            if (!IsGenerated(relative, path))
            {
                yield return (path, relative);
            }
        }
    }

    /// <summary>Generated sources are regenerated, never hand-edited, so no source rule can be applied to them.</summary>
    private static bool IsGenerated(string relative, string path) =>
        relative.Contains("/obj/", StringComparison.Ordinal)
        || relative.Contains("/bin/", StringComparison.Ordinal)
        || relative.Contains("/Migrations/", StringComparison.Ordinal)
        || relative.EndsWith(".Designer.cs", StringComparison.Ordinal)
        || relative.EndsWith(".g.cs", StringComparison.Ordinal)
        || HasGeneratedHeader(path);

    private static bool HasGeneratedHeader(string path)
    {
        using var reader = new StreamReader(path);
        var buffer = new char[400];
        var read = reader.ReadBlock(buffer, 0, buffer.Length);
        return new string(buffer, 0, read).Contains("<auto-generated", StringComparison.Ordinal);
    }
}
