namespace XE_Local_AI_Engine.Client.Persistence.Entities;

using XE_Local_AI_Engine.Client.Persistence.Stores;

/// <summary>
///     One question a benchmark project asks. A project holds 1..N of them and a single item is the degenerate case:
///     a project created before task items existed materializes item 0 from its <see cref="BenchmarkProject.CoreTaskJson" />
///     and ranks exactly as it always did.
/// </summary>
internal sealed record class BenchmarkTaskItem
{
    /// <summary>The case identity. A generated long-context case is an ordinary item with its own id, not an anonymous sub-item.</summary>
    public Guid Id { get; set; }

    public Guid ProjectId { get; set; }

    /// <summary>
    ///     <see langword="null" /> for an authored item; set on a case generated by expanding a generator item, and
    ///     pointing at that generator. Self-referencing, so deletion walks children before parents — this connection
    ///     does not enforce foreign keys and no cascade fires.
    /// </summary>
    public Guid? ParentItemId { get; set; }

    /// <summary>
    ///     0-based display position, unique per project and never renumbered on delete (a gap is fine). Not a scoring
    ///     input and deliberately absent from <see cref="BenchmarkProject.TaskItemSetHash" />: reordering changes no
    ///     question, so it must not unrank a history of answers.
    /// </summary>
    public int Index { get; set; }

    /// <summary><see cref="Stores.BenchmarkTaskItemKinds" />. Only a LEAF kind is a run target.</summary>
    public string Kind { get; set; } = BenchmarkTaskItemKinds.Prompt;

    /// <summary>1..n, incremented on every mutation of this item and hashed into <see cref="InputHash" />.</summary>
    public int Revision { get; set; }

    /// <summary>
    ///     <c>v1:</c> + SHA-256 over exactly what this item asks (kind, revision, and the four payloads). PLAINTEXT,
    ///     because the ranking read compares a run's frozen copy of it against this column without ever decrypting a
    ///     payload. Recomputed by the store on every write.
    /// </summary>
    public string InputHash { get; set; } = string.Empty;

    /// <summary>Whether this item enters the project's ranked mean. False for a probe measured on its own axis.</summary>
    public bool CountsTowardScore { get; set; } = true;

    /// <summary>
    ///     Plaintext UTF-8 JSON while tracked; encrypted at rest with node-scoped AAD column
    ///     <c>benchmark_task_item_prompt_json</c>.
    /// </summary>
    public byte[] PromptJson { get; set; } = [];

    /// <summary>
    ///     Plaintext UTF-8 JSON while tracked; encrypted at rest with node-scoped AAD column
    ///     <c>benchmark_task_item_reference_json</c>. Overrides the judge policy's reference answer for this item.
    /// </summary>
    public byte[]? ReferenceAnswerJson { get; set; }

    /// <summary>
    ///     Plaintext UTF-8 JSON while tracked; encrypted at rest with node-scoped AAD column
    ///     <c>benchmark_task_item_verifier_json</c>. Per-criterion overrides of the policy's verifier config — it can
    ///     carry expected answers and test code, so it is never plaintext.
    /// </summary>
    public byte[]? VerifierConfigJson { get; set; }

    /// <summary>
    ///     Plaintext UTF-8 JSON while tracked; encrypted at rest with node-scoped AAD column
    ///     <c>benchmark_task_item_generator_json</c>. The parameters a generator item expands into its child cases.
    /// </summary>
    public byte[]? GeneratorConfigJson { get; set; }

    public long Version { get; set; }
    public long CreatedAtUtc { get; set; }
    public long UpdatedAtUtc { get; set; }
}
