namespace XE_Local_AI_Engine.Client.Services.Sandbox.Implementation.Launch.Isolation;

using System.Globalization;
using System.Text;

/// <summary>The four <c>/etc</c> entries the jail is given, generated byte for byte rather than bound from the host.</summary>
/// <remarks>
///     The host's <c>/etc</c> is local configuration and account data — <c>shadow</c>, <c>sudoers</c>, <c>ssh</c>, machine identity — so
///     even a read-only bind hands the sandbox the machine's user list, while omitting it breaks <c>getpwuid</c> on the running uid, which
///     <c>os.path.expanduser</c>, <c>getpass.getuser</c> and several build tools go through. <c>nsswitch.conf</c> says <c>files</c> for
///     every database so glibc cannot consult a <c>systemd</c> backend on a bus the jail cannot reach and turn a lookup into a timeout,
///     and <c>hosts</c> resolves <c>localhost</c> without DNS. The bytes are a security surface and are pinned by unit test.
/// </remarks>
internal static class SandboxSyntheticEtc
{
    /// <summary>The account name the single mapped uid carries inside the jail.</summary>
    public const string AccountName = "xe";

    /// <summary>
    ///     <c>/etc/passwd</c>: root, so a lookup of uid 0 does not fail, and the one account the workload runs as, whose home is the
    ///     writable jail.
    /// </summary>
    /// <remarks>
    ///     Both shells are <c>nologin</c>: nothing in the jail is meant to start an interactive login, and naming a real shell there would
    ///     only make it easier for a tool to try.
    /// </remarks>
    public static byte[] BuildPasswd(uint userId, uint groupId)
    {
        return Encoding.UTF8.GetBytes(string.Create(CultureInfo.InvariantCulture,
            $"root:x:0:0:root:/root:/sbin/nologin\n{AccountName}:x:{userId}:{groupId}:{AccountName}:/work/home:/sbin/nologin\n"));
    }

    /// <summary><c>/etc/group</c>: root and the single group the mapped uid belongs to.</summary>
    public static byte[] BuildGroup(uint groupId)
    {
        return Encoding.UTF8.GetBytes(string.Create(CultureInfo.InvariantCulture,
            $"root:x:0:\n{AccountName}:x:{groupId}:\n"));
    }

    /// <summary><c>/etc/nsswitch.conf</c>: files only, so no lookup reaches for a service the jail cannot talk to.</summary>
    public static byte[] BuildNameServiceSwitch()
    {
        return "passwd: files\ngroup: files\nshadow: files\nhosts: files\n"u8.ToArray();
    }

    /// <summary><c>/etc/hosts</c>: loopback only. The jail has an empty network namespace; there is nothing else to name.</summary>
    public static byte[] BuildHosts()
    {
        return "127.0.0.1 localhost\n::1 localhost ip6-localhost ip6-loopback\n"u8.ToArray();
    }
}
