namespace XE_Local_AI_Engine.Client.Services.Sandbox.Implementation.Launch.Isolation;

using System.Globalization;
using System.Text;

/// <summary>
///     The four <c>/etc</c> entries the jail is given, generated byte for byte rather than bound from the host.
///     <para>
///         The host's <c>/etc</c> is not a system directory the workload needs — it is a directory of local
///         configuration and account data (<c>shadow</c>, <c>sudoers</c>, <c>ssh</c>, machine identity). Binding it
///         read-only would still hand the sandbox the machine's user list. Omitting it entirely breaks ordinary
///         library calls: <c>getpwuid</c> on the running uid is what Python's <c>os.path.expanduser</c>,
///         <c>getpass.getuser</c> and several build tools go through, and with no <c>passwd</c> at all they raise
///         instead of returning. So the jail gets a minimal invented account database describing exactly the one uid
///         that exists inside it, and nothing else.
///     </para>
///     <para>
///         <c>nsswitch.conf</c> says <c>files</c> for every database on purpose. Without it glibc may consult
///         <c>systemd</c> or <c>nss-mymachines</c> backends that try to talk to a bus the jail cannot reach, turning a
///         name lookup into a multi-second timeout. <c>hosts</c> exists so <c>localhost</c> resolves without DNS,
///         which matters because the jail has no network at all and a DNS attempt would otherwise hang.
///     </para>
///     <para>
///         The bytes are pinned by unit test. They are a security surface — this is the account database the workload
///         reads — and a change to them should be a deliberate edit to an assertion, not a silent drift.
///     </para>
/// </summary>
internal static class SandboxSyntheticEtc
{
    /// <summary>The account name the single mapped uid carries inside the jail.</summary>
    public const string AccountName = "xe";

    /// <summary>
    ///     <c>/etc/passwd</c>: root (so a lookup of uid 0 does not fail) and the one account the workload runs as,
    ///     whose home is the writable jail. Both shells are <c>nologin</c>; nothing in the jail is meant to start an
    ///     interactive login, and naming a real shell there would only make it easier for a tool to try.
    /// </summary>
    public static byte[] BuildPasswd(uint userId, uint groupId)
    {
        return Encoding.UTF8.GetBytes(string.Create(CultureInfo.InvariantCulture,
            $"root:x:0:0:root:/root:/sbin/nologin\n{AccountName}:x:{userId}:{groupId}:{AccountName}:/work/home:/sbin/nologin\n"));
    }

    /// <summary><c>/etc/group</c>: root and the single group the mapped uid belongs to.</summary>
    public static byte[] BuildGroup(uint groupId)
    {
        return Encoding.UTF8.GetBytes(string.Create(CultureInfo.InvariantCulture,
            $"root:x:0:\n{AccountName}:x:{groupId}:\n"));
    }

    /// <summary><c>/etc/nsswitch.conf</c>: files only, so no lookup reaches for a service the jail cannot talk to.</summary>
    public static byte[] BuildNameServiceSwitch()
    {
        return "passwd: files\ngroup: files\nshadow: files\nhosts: files\n"u8.ToArray();
    }

    /// <summary><c>/etc/hosts</c>: loopback only. The jail has an empty network namespace; there is nothing else to name.</summary>
    public static byte[] BuildHosts()
    {
        return "127.0.0.1 localhost\n::1 localhost ip6-localhost ip6-loopback\n"u8.ToArray();
    }
}
