using System.Text;
using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.RegularExpressions;
using YamlDotNet.Serialization;

// Build-time transform: vendored agency-agents .md  ->  agent-templates.seed.json
//
// Usage:
//   dotnet run --project tools/AgentTemplateGenerator -- <sourcesRoot> <outputJson> <upstreamSha>
//
//   <sourcesRoot> = .../Templates/sources/agency-agents   (contains <division>/<slug>.md)
//   <outputJson>  = .../Templates/agent-templates.seed.json  (embedded resource, do not hand-edit)
//   <upstreamSha> = the pinned commit SHA the .md were vendored from
//
// The vendored set IS the curation: every .md under <sourcesRoot> becomes one template.
// Bodies are emitted VERBATIM (preserve the audited base). Output is sorted by slug for a
// stable, reviewable diff. Malformed files are skipped + logged, never fatal.

if (args.Length < 3)
{
    Console.Error.WriteLine("usage: AgentTemplateGenerator <sourcesRoot> <outputJson> <upstreamSha>");
    return 2;
}

var sourcesRoot = args[0];
var outputJson = args[1];
var sha = args[2];

if (!Directory.Exists(sourcesRoot))
{
    Console.Error.WriteLine($"sources root not found: {sourcesRoot}");
    return 2;
}

var deserializer = new DeserializerBuilder().Build();
var frontmatter = new Regex(
    "^---\\s*\\r?\\n(.*?)\\r?\\n---\\s*\\r?\\n?(.*)$",
    RegexOptions.Singleline | RegexOptions.CultureInvariant);

var templates = new List<Template>();
var skipped = 0;

foreach (var file in Directory
             .EnumerateFiles(sourcesRoot, "*.md", SearchOption.AllDirectories)
             .OrderBy(static p => p, StringComparer.Ordinal))
{
    var text = File.ReadAllText(file);
    var match = frontmatter.Match(text);
    if (!match.Success)
    {
        Console.Error.WriteLine($"SKIP (no frontmatter): {file}");
        skipped++;
        continue;
    }

    Dictionary<string, object?> fm;
    try
    {
        fm = deserializer.Deserialize<Dictionary<string, object?>>(match.Groups[1].Value)
             ?? new Dictionary<string, object?>();
    }
    catch (Exception ex)
    {
        Console.Error.WriteLine($"SKIP (yaml {ex.GetType().Name}): {file}");
        skipped++;
        continue;
    }

    var name = Scalar(fm, "name");
    var description = Scalar(fm, "description");
    var body = match.Groups[2].Value.Trim();

    if (string.IsNullOrWhiteSpace(name) || string.IsNullOrWhiteSpace(body))
    {
        Console.Error.WriteLine($"SKIP (missing name/body): {file}");
        skipped++;
        continue;
    }

    var slug = Path.GetFileNameWithoutExtension(file);
    var division = Path.GetFileName(Path.GetDirectoryName(file)!);
    var relative = Path.GetRelativePath(sourcesRoot, file).Replace('\\', '/');
    var estimatedTokens = (int)Math.Ceiling(body.Length / 4.0);

    templates.Add(new Template(
        slug,
        name!.Trim(),
        string.IsNullOrWhiteSpace(description) ? null : description!.Trim(),
        division,
        body,
        estimatedTokens,
        OriginalTools(fm),
        relative));
}

templates = templates.OrderBy(static t => t.Slug, StringComparer.Ordinal).ToList();

var document = new SeedDocument(
    new SourceInfo(
        "msitarzewski/agency-agents",
        sha,
        "MIT",
        "Copyright (c) 2025 AgentLand Contributors",
        "GENERATED by tools/AgentTemplateGenerator from the vendored .md under sources/. Do not hand-edit; re-run the generator."),
    templates);

var jsonOptions = new JsonSerializerOptions
{
    WriteIndented = true,
    PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
    Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
};

File.WriteAllText(outputJson, JsonSerializer.Serialize(document, jsonOptions) + "\n", new UTF8Encoding(false));

Console.WriteLine($"wrote {templates.Count} template(s) to {outputJson} (skipped {skipped})");
return 0;

static string? Scalar(Dictionary<string, object?> fm, string key)
    => fm.TryGetValue(key, out var value) && value is not null ? value.ToString() : null;

static IReadOnlyList<string> OriginalTools(Dictionary<string, object?> fm)
{
    if (!fm.TryGetValue("tools", out var value) || value is null)
    {
        return Array.Empty<string>();
    }

    if (value is IEnumerable<object?> list)
    {
        return list.Where(static x => x is not null).Select(static x => x!.ToString()!).ToArray();
    }

    return value.ToString()!
                .Split([',', ' '], StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
}

internal sealed record SeedDocument(SourceInfo Source, IReadOnlyList<Template> Templates);

internal sealed record SourceInfo(string Repo, string Sha, string License, string Copyright, string Note);

internal sealed record Template(
    string Slug,
    string Name,
    string? Description,
    string Division,
    string Instructions,
    int EstimatedPromptTokens,
    IReadOnlyList<string> OriginalTools,
    string SourceFile);
