namespace XE_Local_AI_Engine.Client.Services.Knowledge;

/// <summary>
///     Everything the knowledge document store needs to durably persist one uploaded corpus file: the raw bytes plus the
///     already-computed metadata. The <paramref name="DocumentId" /> is server-generated by the caller; the store
///     encrypts the bytes to disk and writes the <c>knowledge_documents</c> row (status <c>Pending</c>) over the raw-SQL
///     path, deduping on <paramref name="ContentHash" />. Chunk, section, and vector persistence are separate lanes.
/// </summary>
public sealed record KnowledgeDocumentInput(
    Guid DocumentId,
    string OriginalFileName,
    string MimeType,
    string Extension,
    long SizeBytes,
    string ContentHash,
    ReadOnlyMemory<byte> Content,
    string EmbeddingModel);
