namespace XE_Local_AI_Engine.Client.Services.Knowledge;

/// <summary>
///     Everything the knowledge document store needs to durably persist one uploaded corpus file: the raw bytes plus the
///     already-computed metadata.
/// </summary>
/// <remarks>
///     The <see cref="DocumentId" /> is server-generated by the caller; the store encrypts the bytes to disk and writes
///     the <c>knowledge_documents</c> row (status <c>Pending</c>) over the raw-SQL path. Uploads dedupe on
///     <see cref="ContentHash" />; repository sources use their normalized <see cref="SourceKind" /> +
///     <see cref="SourceId" /> + <see cref="SourcePath" /> identity. Chunk, section, and vector persistence are separate
///     lanes.
/// </remarks>
public sealed class KnowledgeDocumentInput
{
    public required Guid DocumentId { get; init; }

    public required string OriginalFileName { get; init; }

    public required string MimeType { get; init; }

    public required string Extension { get; init; }

    public required long SizeBytes { get; init; }

    public required string ContentHash { get; init; }

    public required ReadOnlyMemory<byte> Content { get; init; }

    public required string EmbeddingModel { get; init; }

    public string CollectionId { get; init; } = KnowledgeCollectionScope.DefaultId;

    public string? SourcePath { get; init; }

    public string SourceKind { get; init; } = "upload";

    public string? SourceId { get; init; }
}
