import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

/**
 * Generates the third-party license list rendered in the About dialog's Licenses tab.
 *
 * Frontend packages come from the complete production tree reported by
 * `pnpm licenses list --prod --json`. Backend NuGet packages come from the complete
 * transitive Release tree reported by `nuget-license`. Missing tooling, restore
 * failures, and unreviewable license metadata fail closed so a stale or partial list
 * cannot be presented as release evidence.
 */

const scriptDir = dirname(fileURLToPath(import.meta.url));
const reactRoot = resolve(scriptDir, "..");
const repoRoot = resolve(reactRoot, "..");
const solutionPath = resolve(repoRoot, "XE-Local-AI-Engine.slnx");
const nugetOverridePath = resolve(repoRoot, "scripts/compliance/nuget-license-overrides.json");
const outputPath = resolve(reactRoot, "src/features/about/data/third-party-licenses.generated.json");

const GENERATED_NOTICE =
	"AUTO-GENERATED by scripts/GenerateLicenses.mjs (pnpm run licenses:generate). DO NOT EDIT BY HAND.";

// Build-time analyzers / orchestration packages that ship with no runtime artifacts.
const BACKEND_IGNORED_PACKAGES = [
	"Meziantou.Analyzer",
	"SonarAnalyzer.CSharp",
	"Microsoft.CodeAnalysis.BannedApiAnalyzers",
	"NetArchTest.Rules",
];

// Projects that are never shipped to end users (tests, fixtures, dev orchestration).
const BACKEND_EXCLUDED_PROJECTS = ["*Tests*", "*Testing*", "*AppHost*"];

/**
 * @typedef {object} ThirdPartyPackage
 * @property {string} id
 * @property {string} name
 * @property {string} version
 * @property {string} license
 * @property {string} [homepageUrl]
 * @property {"frontend" | "backend"} source
 */

/** @returns {string | undefined} */
function normalizeUrl(value) {
	if (typeof value !== "string") {
		return undefined;
	}

	const trimmed = value.trim();
	return trimmed === "" ? undefined : trimmed;
}

/** @returns {string} */
export function normalizeLicense(value) {
	const trimmed = typeof value === "string" ? value.trim() : "";
	if (trimmed === "") {
		throw new Error("Package is missing license metadata");
	}

	return trimmed;
}

/**
 * Collects the complete production frontend dependency tree via pnpm's own license reader.
 * @returns {ThirdPartyPackage[]}
 */
function collectFrontendPackages() {
	// On Windows pnpm is a .cmd shim; Node refuses to spawn .cmd/.bat directly (EINVAL) and
	// won't resolve the bare name (ENOENT), so go through the shell there.
	const isWindows = process.platform === "win32";
	const result = spawnSync("pnpm", ["licenses", "list", "--prod", "--json"], {
		cwd: reactRoot,
		encoding: "utf8",
		maxBuffer: 64 * 1024 * 1024,
		shell: isWindows,
	});

	if (result.status !== 0 || typeof result.stdout !== "string" || result.stdout.trim() === "") {
		throw new Error(`pnpm licenses list failed: ${result.stderr || result.error || "unknown error"}`);
	}

	/** @type {Record<string, Array<{ name: string; versions?: string[]; license?: string; homepage?: string }>>} */
	const grouped = JSON.parse(result.stdout);
	/** @type {ThirdPartyPackage[]} */
	const packages = [];

	for (const entries of Object.values(grouped)) {
		for (const entry of entries) {
			const versions = Array.isArray(entry.versions) && entry.versions.length > 0 ? entry.versions : ["unknown"];

			for (const version of versions) {
				packages.push({
					id: `frontend:${entry.name}@${version}`,
					name: entry.name,
					version,
					license: normalizeLicense(entry.license),
					homepageUrl: normalizeUrl(entry.homepage),
					source: "frontend",
				});
			}
		}
	}

	return packages;
}

/**
 * Restores the solution pinned to the Release configuration so the license scan is deterministic.
 *
 * nuget-license reads each project's restore assets (`project.assets.json`), which reflect the LAST
 * restore's `$(Configuration)`. A Debug restore pulls in Debug-only conditional packages
 * (Microsoft.Agents.AI.DevUI / Hosting / Hosting.OpenAI — see the `'$(Configuration)' == 'Debug'`
 * PackageReferences in XE-Local-AI-Engine.Client.csproj and XE-Local-AI-Engine.AI.Agent.csproj) that
 * are compiled out of Release and never ship. Forcing a Release restore here pins the assets so the
 * generated list only ever reflects the shipped (Release) package set, regardless of what a prior
 * build/IDE left restored.
 */
function restoreSolutionForRelease() {
	const result = spawnSync("dotnet", ["restore", solutionPath, "-p:Configuration=Release", "--verbosity", "quiet"], {
		cwd: repoRoot,
		encoding: "utf8",
		maxBuffer: 64 * 1024 * 1024,
	});

	if (result.error) {
		throw new Error(`dotnet not available: ${result.error.message}`);
	}

	if (result.status !== 0) {
		throw new Error(`dotnet restore (Release) failed (exit ${result.status}): ${result.stderr || "no output"}`);
	}
}

/**
 * Collects shipped backend NuGet packages via the nuget-license dotnet tool.
 * @returns {ThirdPartyPackage[]}
 */
function collectBackendPackages() {
	if (!existsSync(solutionPath)) {
		throw new Error(`solution not found: ${solutionPath}`);
	}

	// Pin the restore to Release before scanning so Debug-only packages never leak into the shipped list.
	restoreSolutionForRelease();

	const args = [
		"nuget-license",
		"--input",
		solutionPath,
		"--output",
		"Json",
		"--include-transitive",
		"--exclude-publish-false",
		"--override-package-information",
		nugetOverridePath,
		"--exclude-projects-matching",
		BACKEND_EXCLUDED_PROJECTS.join(";"),
		"--ignored-packages",
		BACKEND_IGNORED_PACKAGES.join(";"),
	];

	// Run from the repo root so the dotnet-tools.json manifest resolves.
	const result = spawnSync("dotnet", args, {
		cwd: repoRoot,
		encoding: "utf8",
		maxBuffer: 64 * 1024 * 1024,
	});

	if (result.error) {
		throw new Error(`dotnet not available: ${result.error.message}`);
	}

	if (result.status !== 0 || typeof result.stdout !== "string" || result.stdout.trim() === "") {
		throw new Error(`nuget-license failed (exit ${result.status}): ${result.stderr || "no output"}`);
	}

	const jsonStart = result.stdout.indexOf("[");
	if (jsonStart < 0) {
		throw new Error("nuget-license produced no JSON array");
	}

	/** @type {Array<{ PackageId: string; PackageVersion: string; License?: string; PackageProjectUrl?: string; LicenseUrl?: string }>} */
	const parsed = JSON.parse(result.stdout.slice(jsonStart));

	return parsed.map((pkg) => ({
		id: `backend:${pkg.PackageId}@${pkg.PackageVersion}`,
		name: pkg.PackageId,
		version: pkg.PackageVersion,
		license: normalizeLicense(pkg.License),
		homepageUrl: normalizeUrl(pkg.PackageProjectUrl) ?? normalizeUrl(pkg.LicenseUrl),
		source: "backend",
	}));
}

/**
 * @param {ThirdPartyPackage[]} packages
 * @returns {ThirdPartyPackage[]}
 */
export function dedupeAndSort(packages) {
	/** @type {Map<string, ThirdPartyPackage>} */
	const byId = new Map();
	for (const pkg of packages) {
		if (["UNKNOWN", "NOASSERTION"].includes(pkg.license.trim().toUpperCase())) {
			throw new Error(`Package ${pkg.id} has license metadata that is not reviewable: ${pkg.license}`);
		}

		byId.set(pkg.id, pkg);
	}

	return [...byId.values()].sort((a, b) => {
		const byName = a.name.localeCompare(b.name, "en", { sensitivity: "base" });
		if (byName !== 0) {
			return byName;
		}

		const byVersion = a.version.localeCompare(b.version, "en", { numeric: true });
		return byVersion !== 0 ? byVersion : a.source.localeCompare(b.source);
	});
}

function main() {
	const frontend = collectFrontendPackages();
	process.stdout.write(`frontend packages: ${frontend.length}\n`);

	const backend = collectBackendPackages();
	process.stdout.write(`backend packages: ${backend.length}\n`);

	const packages = dedupeAndSort([...frontend, ...backend]);
	const payload = {
		$generated: GENERATED_NOTICE,
		packages,
	};

	mkdirSync(dirname(outputPath), { recursive: true });
	writeFileSync(outputPath, `${JSON.stringify(payload, null, "\t")}\n`);
	process.stdout.write(`wrote ${packages.length} packages to ${outputPath}\n`);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
	main();
}
